import XCTest
@testable import WTRLWorld
@testable import WTRLVehicle
@testable import WTRLGarage
@testable import WTRLAudio
final class Rev16DeepEngineTests:XCTestCase {
 func testWetPaintLosesGrip(){var c=ClimateState();c.waterFilmMm=1.5;var s=RoadPatchSample();s.surface = .roadPaint;s.waterFilmMm=1.5;let r=SurfaceClimateAuthority.resolve(samples:[s,s,s,s],speedMps:28,tirePressureKPa:230,treadDepthMm:5,climate:c);XCTAssertLessThan(r.effectiveMu,0.4)}
 func testWaterSpeedAndTreadIncreaseHydroRisk(){var c=ClimateState();c.waterFilmMm=2.5;var s=RoadPatchSample();s.surface = .urbanAsphalt;let slow=SurfaceClimateAuthority.resolve(samples:[s],speedMps:10,tirePressureKPa:220,treadDepthMm:7,climate:c);let fast=SurfaceClimateAuthority.resolve(samples:[s],speedMps:45,tirePressureKPa:280,treadDepthMm:1.5,climate:c);XCTAssertLessThan(fast.effectiveMu,slow.effectiveMu)}
 func testVaporPressureRisesWithHumidity(){XCTAssertGreaterThan(SurfaceClimateAuthority.vaporPressureKPa(ambientC:30,humidity01:0.8),SurfaceClimateAuthority.vaporPressureKPa(ambientC:30,humidity01:0.2))}
 func testVintageStructureFlexAndFatigue(){var st=ChassisStructureState();var p=ChassisStructureSpec();p.torsionalStiffnessNmPerDeg=5200;for _ in 0..<2000{_ = StructuralFatigueAuthority.step(state:&st,spec:p,drivelineReactionNm:950,lateralLoadTransferTorqueNm:4500,dt:1.0/120)};let o=StructuralFatigueAuthority.step(state:&st,spec:p,drivelineReactionNm:950,lateralLoadTransferTorqueNm:4500,dt:1.0/120);XCTAssertGreaterThan(abs(o.twistDeg),0.5);XCTAssertGreaterThan(st.fatigueDamage01,0)}
 func testCoolingHeatSoak(){var s=CoolingThermalState();for _ in 0..<1200{CoolingThermalAuthority.step(state:&s,engineWasteHeatKW:150,airSpeedMps:1,ambientC:35,radiatorCapacityKWPerC:0.08,dt:0.05)};XCTAssertGreaterThan(s.coolantC,95);XCTAssertGreaterThan(s.heatSoak01,0)}
 func testHubAbuseAccumulatesDamage(){var s=HubBearingState();for _ in 0..<1000{HubBearingAuthority.step(state:&s,radialLoadN:9000,lateralLoadN:7000,misalignmentDeg:1.2,dt:0.1)};XCTAssertGreaterThan(s.damage01,0);XCTAssertGreaterThan(s.temperatureC,35)}
 func testOversizedSwapRejected(){let c=ChassisPackagingEnvelope(bayLengthMm:710,bayWidthMm:620,bayHeightMm:650,tunnelWidthMm:360,frontAxleCapacityKg:550,orientation:.longitudinal);let e=PowertrainPackage(lengthMm:900,widthMm:780,heightMm:700,massKg:320,gearboxWidthMm:450,orientation:.longitudinal,sump:.front);XCTAssertFalse(UniversalFabricationAuthority.assess(chassis:c,powertrain:e).feasible)}
 func testMarginalSwapCreatesRealWork(){let c=ChassisPackagingEnvelope(bayLengthMm:800,bayWidthMm:700,bayHeightMm:680,tunnelWidthMm:360,frontAxleCapacityKg:650,orientation:.longitudinal);let e=PowertrainPackage(lengthMm:790,widthMm:730,heightMm:660,massKg:280,gearboxWidthMm:420,orientation:.longitudinal,sump:.front);let a=UniversalFabricationAuthority.assess(chassis:c,powertrain:e);XCTAssertTrue(a.feasible);XCTAssertTrue(a.operations.contains(.subframeFabrication));XCTAssertTrue(a.operations.contains(.tunnelClearance));XCTAssertTrue(a.operations.contains(.oilPanConversion))}
 func testAudioTracksRPM(){let p=EngineAcousticProfile(cylinderCount:8,firingEventsPerCycle:8,runnerLengthM:0.55,crossPlane:true,inductionOpenness01:0.8);let a=EngineHarmonicAuthority.resolve(rpm:3000,throttle01:1,manifoldAbsBar:1,profile:p);let b=EngineHarmonicAuthority.resolve(rpm:6000,throttle01:1,manifoldAbsBar:1,profile:p);XCTAssertEqual(b.fundamentalHz,a.fundamentalHz*2,accuracy:0.001);XCTAssertEqual(a.harmonics.count,8)}
 func testInductionMissionIsEngineeringLoop(){let m=FactionMissionCatalog.inductionWar;XCTAssertEqual(m.faction,.siliconSyndicate);XCTAssertTrue(m.objectives.contains(.diagnose));XCTAssertTrue(m.objectives.contains(.inspect));XCTAssertTrue(m.requiresWetSurface)}
}
