import Testing
@testable import WTRLVehicle
@testable import WTRLGarage
@testable import WTRLApp
@testable import WTRLCareer

@Test func clutchSlipBuildsHeatAndWear(){var s=ClutchFrictionState();let before=s.temperatureC;let o=DynamicClutchAuthority.step(state:&s,spec:.init(),engineTorqueNm:700,engineOmega:420,gearboxInputOmega:350,pedal01:1,gearRatio:1.78,finalDrive:3.55,dt:0.1);#expect(o.slipRPM>100);#expect(s.temperatureC>before);#expect(s.wear01>0)}
@Test func suspensionKinematicsMigratesGeometry(){var p=KinematicSuspensionProfile();p.camberGainDegPerM = -20;let r=SuspensionKinematicsAuthority.evaluate(p,jounceM:0.05,oppositeJounceM:-0.02);#expect(r.camberDeg < p.staticCamberDeg);#expect(r.rollCenterHeightM != p.staticRollCenterM)}
@Test func timingVignetteRequiresToolsAndRunningEngine(){var s=IgnitionTimingState();#expect(IgnitionTimingAuthority.adjust(&s,deltaDeg:1,targetDeg:12) == .connectTimingLight);s.timingLightOnCylinderOne=true;#expect(IgnitionTimingAuthority.adjust(&s,deltaDeg:1,targetDeg:12) == .startEngine);s.engineRunning=true;let r=IgnitionTimingAuthority.adjust(&s,deltaDeg:5,targetDeg:12);#expect(r == .withinCalibrationWindow)}
@Test func bracketAuditFindsMultipleViolations(){let b=CompetitionBracket(id:"C",maximumPowerKW:194,minimumMassKg:1350,maximumTireWidthMM:215,forcedInductionAllowed:false,maximumBuildCredits:8500);let r=BracketAuditAuthority.reasons(powerKW:220,massKg:1380,tireWidthMM:205,forcedInduction:false,buildCredits:11200,bracket:b);#expect(r.contains("power"));#expect(r.contains("budget"))}
@Test func rivalBrainIsDeterministic(){var a=RivalBrainState(),b=RivalBrainState();var d=RivalDriverAttributes();d.reactionTimeSec=0.3;d.aggression01=0.8;d.composure01=0.3;d.brakingSafetyMarginM=4;let c=RivalTrackContext(distanceToApexM:45,brakingDistanceBeforeApexM:45,trackWidthM:10,cornerRadiusM:40);let x=DeterministicRivalBrain.decide(state:&a,driver:d,context:c,playerDeltaM:-2,reputation01:0.9,eventSeed:42);let y=DeterministicRivalBrain.decide(state:&b,driver:d,context:c,playerDeltaM:-2,reputation01:0.9,eventSeed:42);#expect(x==y)}
@Test func oneCarTruthPersistsAcrossActivities(){var g=GarageState();let id="hero";var i=UnifiedBlackridgeVehicleInput();i.throttle=1;i.engineRPM=5000;i.environment.rearLeft.effectiveMu=0.45;_ = OneCarPhysicalTruthAuthority.step(vehicleId:id,activity:.blackridge,garage:&g,input:i,differentialSetup:.init(),dt:0.05);let afterRoad=g.vehiclePhysicalTruth[id]!;_ = OneCarPhysicalTruthAuthority.step(vehicleId:id,activity:.dyno,garage:&g,input:i,differentialSetup:.init(),dt:0.05);let afterDyno=g.vehiclePhysicalTruth[id]!;#expect(afterDyno.distanceM >= afterRoad.distanceM);#expect(g.damageLedgers[id] != nil)}
