import Testing
@testable import WTRLVehicle
@testable import WTRLGarage
@testable import WTRLWorld

@Test func fluidThermalsHeatAndCanAccumulateBearingRisk(){var s=EngineFluidThermalState();var i=EngineFluidThermalInput();i.rpm=6500;i.load01=1;i.vehicleSpeedMps=0;i.ambientC=35;i.dt=0.05;for _ in 0..<1200{EngineFluidThermalAuthority.step(state:&s,input:i)};#expect(s.blockC>85);#expect(s.coolantC>82);#expect(s.oilC>90)}
@Test func elastokinematicsChangesCamberAndToeWithJounce(){let a=ElastokinematicAuthority.resolve(spec:.init(),jounceM:0,lateralForceN:0,longitudinalForceN:0);let b=ElastokinematicAuthority.resolve(spec:.init(),jounceM:0.05,lateralForceN:4000,longitudinalForceN:0);#expect(b.camberDeg != a.camberDeg);#expect(b.toeDeg != a.toeDeg)}
@Test func cornerWeightAdjustmentPreservesMassAndChangesCross(){let base=CornerScaleWeights(flKg:380,frKg:375,rlKg:345,rrKg:350);let x=CornerWeightAuthority.resolve(base:base,perchAdjustMM:(8,0,0,0),springRateNPerMM:85);#expect(abs(x.totalKg-base.totalKg)<0.001);#expect(x.crossWeight01 != base.crossWeight01)}
@Test func sanTrianaIsAdditionalCountyConnectedToBlackridge(){#expect(OpenWorldCountyID.allCases.contains(.blackridge));#expect(OpenWorldCountyID.allCases.contains(.sanTriana));#expect(SanTrianaCountyAuthority.blackridgeConnection.from == .blackridge);#expect(SanTrianaCountyAuthority.blackridgeConnection.to == .sanTriana);#expect(SanTrianaCountyAuthority.zones.count >= 5)}
@Test func sanTrianaTrafficUsesHysteresis(){let p=TrafficGridPolicy();#expect(SanTrianaTrafficAuthority.tier(distanceM:60,currentlyFullPhysics:false,policy:p) == .fullPhysics);#expect(SanTrianaTrafficAuthority.tier(distanceM:75,currentlyFullPhysics:true,policy:p) == .fullPhysics);#expect(SanTrianaTrafficAuthority.tier(distanceM:100,currentlyFullPhysics:false,policy:p) == .kinematic)}
@Test func carburetorRebuildRejectsBadFloatAndBadTorque(){var s=CarburetorRebuildState();_ = CarburetorRebuildAuthority.advance(&s);_ = CarburetorRebuildAuthority.advance(&s);_ = CarburetorRebuildAuthority.advance(&s);let bad=CarburetorRebuildAuthority.advance(&s,floatMM:14);if case .outOfSpecFloat(let e)=bad{#expect(e>2)}else{Issue.record("bad float not rejected")};_ = CarburetorRebuildAuthority.advance(&s,floatMM:11.2);_ = CarburetorRebuildAuthority.advance(&s);let torque=CarburetorRebuildAuthority.advance(&s,boltTorquesNm:[4.5,4.5,4.5,4.5,4.5,4.5,4.5,7]);#expect(torque == .torquePatternRejected)}
@Test func partServiceInferenceProducesPhysicalWorkflow(){let c=PhysicalPartServiceAuthority.infer(specificationId:"x",family:"BrakeSystem");#expect(c.accessZone == .wheelWell);#expect(c.verification.contains("function-test"))}
