import XCTest
@testable import WTRLVehicle
@testable import WTRLWorld
@testable import WTRLPersistence

final class Rev25PersistentMechanicalTruthTests:XCTestCase {
 func testCurbStrikeBecomesPersistentAlignmentAndLeak(){var s=PersistentVehicleDamageState();let impact=PursuitImpactDamageAuthority.resolve(impulseNs:12000,contactLateral01:0.9,wheelContact:true);let e=PersistentMechanicalDamageAuthority.applyImpact(state:&s,corner:.frontRight,damage:impact);XCTAssertLessThan(s.frontRight.permanentToeShiftDeg,-0.2);XCTAssertGreaterThan(s.frontRight.wheelRunoutMm,1);XCTAssertGreaterThan(s.frontRight.pressureLeakKPaPerMinute,0);XCTAssertFalse(e.isEmpty)}
 func testLeakContinuesAfterImpact(){var s=PersistentVehicleDamageState();s.frontLeft.pressureLeakKPaPerMinute=30;let p=s.frontLeft.tirePressureKPa;for _ in 0..<60 { PersistentMechanicalDamageAuthority.step(state:&s,speedMps:25,lateralG:0.4,ambientC:25,dt:1) };XCTAssertLessThan(s.frontLeft.tirePressureKPa,p-20)}
 func testDamageChangesAlignmentAndGrip(){var d=PersistentCornerDamage();d.permanentToeShiftDeg=1.2;d.tirePressureKPa=100;d.wheelRunoutMm=4;let a=PersistentMechanicalDamageAuthority.adjustedAlignment(base:(-1,0.1),damage:d);XCTAssertEqual(a.toeDeg,1.3,accuracy:0.001);XCTAssertLessThan(PersistentMechanicalDamageAuthority.pressureGripScale(d),0.7)}
 func testInspectionFindsPhysicalEvidence(){var s=PersistentVehicleDamageState();s.frontRight.wheelRunoutMm=5;s.frontRight.wheelBearingTempC=92;s.frontRight.pressureLeakKPaPerMinute=12;let e=MechanicalDamageInspectionAuthority.inspect(s);XCTAssertTrue(e.contains{$0.kind=="dial_indicator"});XCTAssertTrue(e.contains{$0.kind=="bearing_heat"});XCTAssertTrue(e.contains{$0.kind=="pressure_decay"})}
 func testTelemetryUsesHypothesesNotSingleCauseClaims(){var f=MechanicalTelemetryFrame();f.steeringCenterOffsetDeg=0.8;f.wheelRunoutMm=3;let h=MechanicalTelemetryInferenceAuthority.analyze([f,f]);XCTAssertEqual(h.first?.title,"impact-related wheel/alignment change");XCTAssertTrue(h.first?.nextMeasurement.contains("alignment rack") == true)}
 func testTireThermalPressureRisesWithGasTemperature(){var s=MultiLayerTireThermalState();for _ in 0..<200 {MultiLayerTireThermalAuthority.step(state:&s,slipPowerW:5000,verticalLoadN:4000,wheelOmega:80,ambientC:25,roadC:35,dt:0.05)};XCTAssertGreaterThan(s.pressureKPa,s.coldPressureKPa)}
 func testDriveshaftResonanceIsCalibrationDriven(){var s=DriveshaftResonanceState();let o=DriveshaftResonanceAuthority.step(state:&s,shaftRPM:7000,torqueNm:650,chassisTwistDeg:1.5,dt:0.1);XCTAssertGreaterThan(o.criticalRPM,0);XCTAssertGreaterThanOrEqual(o.fractureRisk01,0);XCTAssertLessThanOrEqual(o.fractureRisk01,1)}
 func testUnifiedSolverConsumesPersistentDamage(){var clean=UnifiedBlackridgeVehicleState();var damaged=UnifiedBlackridgeVehicleState();var a=UnifiedBlackridgeVehicleInput();a.throttle=0.8;a.engineRPM=4000;var b=a;b.persistentDamage.rearRight.tirePressureKPa=90;b.persistentDamage.rearRight.wheelRunoutMm=5;b.persistentDamage.frontRight.permanentToeShiftDeg = -1.2;for _ in 0..<180{_ = UnifiedBlackridgeVehicleAuthority.step(state:&clean,input:a,differentialSetup:.init(),dt:1.0/120);_ = UnifiedBlackridgeVehicleAuthority.step(state:&damaged,input:b,differentialSetup:.init(),dt:1.0/120)};XCTAssertNotEqual(clean.lastMaxTireUtilization01,damaged.lastMaxTireUtilization01);XCTAssertNotEqual(clean.tires.rearRight.lateralForceN,damaged.tires.rearRight.lateralForceN)}
 func testPersistentDamageSurvivesSaveRoundTrip() throws {var save=SaveEnvelope();save.world.persistentVehicleDamage["hero-1"] = PersistentVehicleDamageState();save.world.persistentVehicleDamage["hero-1"]?.frontRight.wheelRunoutMm=4.2;let data=try SaveCodec.encode(save);let loaded=try SaveCodec.decode(data);XCTAssertEqual(loaded.world.persistentVehicleDamage["hero-1"]?.frontRight.wheelRunoutMm,4.2)}

}
