import XCTest
@testable import WTRLVehicle
@testable import WTRLGarage
@testable import WTRLWorld
@testable import WTRLPersistence

final class Rev26PhysicalDiagnosisRepairTests:XCTestCase {
    func testImpactCreatesAddressableComponentTruth(){var s=PersistentVehicleDamageState();let d=PursuitImpactDamageAuthority.resolve(impulseNs:12000,contactLateral01:0.9,wheelContact:true);_ = PersistentMechanicalDamageAuthority.applyImpact(state:&s,corner:.frontRight,damage:d);XCTAssertNotNil(s.componentConditions["frontRight.wheel"]);XCTAssertGreaterThan(s.componentConditions["frontRight.tieRod"]?.damage01 ?? 0,0)}
    func testAlignmentRackRequiresPhysicalSetup(){var s=PersistentVehicleDamageState();s.alignment.frontRight.toeDeg = -0.8;let bad=AlignmentRackAuthority.measure(truth:s,setup:.init());XCTAssertFalse(bad.valid);XCTAssertLessThan(bad.confidence01,0.2);var setup=AlignmentRackSetup();setup.vehicleOnRack=true;setup.targetsInstalled=Set(VehicleCorner.allCases);setup.turnPlatesUnlocked=true;setup.steeringWheelHeld=true;setup.suspensionSettled=true;let good=AlignmentRackAuthority.measure(truth:s,setup:setup);XCTAssertTrue(good.valid);XCTAssertEqual(good.alignment.frontRight.toeDeg,-0.8,accuracy:0.001)}
    func testAlignmentDerivesThrustAndCrossValues(){var a=VehicleAlignmentState();a.rearLeft.toeDeg=0.1;a.rearRight.toeDeg=0.5;a.frontLeft.camberDeg = -1.2;a.frontRight.camberDeg = -0.7;XCTAssertEqual(a.thrustAngleDeg,0.2,accuracy:0.001);XCTAssertEqual(a.crossCamberDeg,-0.5,accuracy:0.001)}
    func testDialIndicatorRejectsBadSetup(){var s=DialIndicatorSetup();XCTAssertNil(RunoutDiagnosisAuthority.separate(tireMm:3,rimMm:2,hubMm:0.1,setup:s));s.magneticBaseLocked=true;s.probePreloadMm=0.5;s.zeroed=true;s.fixtureStable=true;XCTAssertEqual(RunoutDiagnosisAuthority.separate(tireMm:3,rimMm:2,hubMm:0.1,setup:s)?.likelySource,"wheel/rim")}
    func testRunoutSeparatesHubSource(){var s=DialIndicatorSetup();s.magneticBaseLocked=true;s.probePreloadMm=0.5;s.zeroed=true;s.fixtureStable=true;XCTAssertEqual(RunoutDiagnosisAuthority.separate(tireMm:3,rimMm:1.5,hubMm:0.8,setup:s)?.likelySource,"hub")}
    func testPressureDecayCompensatesTemperature(){let r=TireLeakDiagnosisAuthority.evaluate(startKPa:220,endKPa:190,minutes:10,startTempC:20,endTempC:20);XCTAssertEqual(r.leakKPaPerMinute,3,accuracy:0.001);let cooling=TireLeakDiagnosisAuthority.evaluate(startKPa:220,endKPa:210,minutes:10,startTempC:40,endTempC:20);XCTAssertLessThan(cooling.leakKPaPerMinute,1)}
    func testEvidenceRedistributesHypotheses(){let h=DiagnosticReasoningAuthority.hypotheses(symptoms:["speed_vibration","pull"],evidence:[.init(kind:"wheel_runout",value:4,unit:"mm",corner:.frontRight)]);XCTAssertEqual(h.first?.cause,.wheelRunout);XCTAssertTrue(h.first?.nextMeasurement.contains("hub runout") == true)}
    func testTieRodReplacementChangesPhysicalTruth(){var s=PersistentVehicleDamageState();s.frontRight.tieRodDamage01=0.8;s.frontRight.permanentToeShiftDeg = -1;PhysicalTruthBridgeAuthority.synchronizeLegacyDamage(&s);let new=ComponentPhysicalCondition(componentId:"frontRight.tieRod",kind:.tieRod,corner:.frontRight);RepairVerificationAuthority.replace(componentId:"frontRight.tieRod",with:new,state:&s);XCTAssertEqual(s.frontRight.tieRodDamage01,0);XCTAssertEqual(s.frontRight.permanentToeShiftDeg,0)}
    func testAlignmentAndSteeringCalibrationMutateSameTruth(){var s=PersistentVehicleDamageState();RepairVerificationAuthority.align(corner:.frontRight,to:.init(casterDeg:5,camberDeg:-0.8,toeDeg:0.05),state:&s);RepairVerificationAuthority.calibrateSteeringCenter(to:0.02,state:&s);XCTAssertEqual(s.frontRight.permanentToeShiftDeg,0.05);XCTAssertEqual(s.alignment.frontRight.casterDeg,5);XCTAssertEqual(s.steeringCenterOffsetDeg,0.02)}
    func testVerificationRequiresSymptomRemoval(){let fail=RepairVerificationAuthority.compare(vehicleId:"hero",before:["steering":1,"runout":4],after:["steering":0.5,"runout":2],limits:["steering":0.1,"runout":0.5]);XCTAssertFalse(fail.originalSymptomResolved);let pass=RepairVerificationAuthority.compare(vehicleId:"hero",before:["steering":1,"runout":4],after:["steering":0.05,"runout":0.2],limits:["steering":0.1,"runout":0.5]);XCTAssertTrue(pass.originalSymptomResolved)}
    func testWorkshopEvidenceAndHistorySurviveSave() throws {var save=SaveEnvelope();let tool=WorkshopTool(id:"dial",kind:.dialIndicator);save.garage.workshopMeasurements["hero"]=[.init(vehicleId:"hero",componentId:"frontRight.wheel",corner:.frontRight,type:.wheelRunout,value:4.2,unit:"mm",tool:tool)];save.garage.serviceHistory["hero"]=[.init(vehicleId:"hero",operation:.inspect,componentIds:["frontRight.wheel"],evidenceIds:[save.garage.workshopMeasurements["hero"]![0].id])];let data=try SaveCodec.encode(save);let loaded=try SaveCodec.decode(data);XCTAssertEqual(loaded.garage.workshopMeasurements["hero"]?.first?.value,4.2);XCTAssertEqual(loaded.garage.serviceHistory["hero"]?.first?.operation,.inspect)}
    func testLegacyDamageDecodeDefaultsNewRev26Fields() throws {let original=PersistentVehicleDamageState();let encoded=try JSONEncoder().encode(original);var object=try XCTUnwrap(JSONSerialization.jsonObject(with:encoded) as? [String:Any]);object.removeValue(forKey:"componentConditions");object.removeValue(forKey:"alignment");object.removeValue(forKey:"chassisDatums");let legacy=try JSONSerialization.data(withJSONObject:object);let d=try JSONDecoder().decode(PersistentVehicleDamageState.self,from:legacy);XCTAssertTrue(d.componentConditions.isEmpty);XCTAssertEqual(d.alignment.frontTotalToeDeg,0)}
}
