import XCTest
@testable import WTRLVehicle
@testable import WTRLGarage
@testable import WTRLDyno
final class Rev30ExecutableHeritageTests:XCTestCase {
 func testAll153VehiclesCompileExecutablePhysics(){ XCTAssertEqual(HeritageLineageEngineeringRev29.vehicleCount,153); for v in HeritageLineageEngineeringRev29.allVehicles { let p=HeritageExecutablePhysicsAuthorityRev30.profile(for:v); XCTAssertEqual(p.fixedStepHz,120); XCTAssertFalse(p.primitiveKinds.isEmpty); XCTAssertFalse(p.faultPrimitives.isEmpty) } }
 func testAll153VehiclesHaveValidAssemblyGraphs(){ for v in HeritageLineageEngineeringRev29.allVehicles { let g=HeritageAssemblyAuthorityRev30.graph(for:v); XCTAssertTrue(g.validationIssues().isEmpty,"\(v.id): \(g.validationIssues())"); XCTAssertGreaterThanOrEqual(g.nodes.count,16) } }
 func testForcedInductionGetsThermalAndBoostFaults(){ let cars=HeritageLineageEngineeringRev29.allVehicles.filter{ let t=($0.powertrainArchitecture+" "+$0.induction).lowercased(); return t.contains("turbo") || t.contains("supercharg")}; XCTAssertFalse(cars.isEmpty); for v in cars { let p=HeritageExecutablePhysicsAuthorityRev30.profile(for:v); XCTAssertTrue(p.faultPrimitives.contains(.chargeHeatSoak)); XCTAssertTrue(p.faultPrimitives.contains(.boostLeak)) } }
 func testFordTripleWideHas27ExecutableVehicles(){ let f=HeritageLineageEngineeringRev29.fordTripleWide.vehicles; XCTAssertEqual(f.count,27); XCTAssertEqual(Set(f.compactMap(\.trackId)),Set(["heavy_iron","homologation","endurance_halo"])); for v in f { XCTAssertTrue(HeritageAssemblyAuthorityRev30.graph(for:v).validationIssues().isEmpty) } }
 func testWorkshopPlansAreEvidenceFirstAndResearchSafe(){ for v in HeritageLineageEngineeringRev29.allVehicles.prefix(40) { for fault in HeritageExecutablePhysicsAuthorityRev30.profile(for:v).faultPrimitives { let p=ExecutableHeritageWorkshopAuthorityRev30.plan(vehicle:v,fault:fault); XCTAssertGreaterThanOrEqual(p.steps.count,2); XCTAssertTrue(p.steps.allSatisfy{$0.sourceStatus != .verifiedReference}) } } }
 func testTelemetryExpectationsCoverEveryExecutableFault(){ for v in HeritageLineageEngineeringRev29.allVehicles { let faults=Set(HeritageExecutablePhysicsAuthorityRev30.profile(for:v).faultPrimitives); let exp=ExecutableHeritageTelemetryAuthorityRev30.expectations(for:v); XCTAssertEqual(Set(exp.map(\.fault)),faults); XCTAssertTrue(exp.allSatisfy{!$0.channels.isEmpty && !$0.signature.isEmpty}) } }
 func testFaultEffectsAreCausalNotNarrativeOnly(){ let e=HeritageExecutablePhysicsAuthorityRev30.effects([.init(.chargeHeatSoak,0.8),.init(.brakeHeatSaturation,0.7),.init(.bearingWear,0.6)]); XCTAssertLessThan(e.torqueScale,1); XCTAssertLessThan(e.brakeScale,1); XCTAssertGreaterThan(e.vibration01,0); XCTAssertGreaterThanOrEqual(e.evidence.count,3) }
 func testAssemblyIdentityIsSharedAcrossVisualAndPhysics(){ for v in HeritageLineageEngineeringRev29.allVehicles { XCTAssertTrue(HeritageAssemblyAuthorityRev30.graph(for:v).nodes.allSatisfy{$0.visualBindingId == $0.physicsBindingId}) } }
}
