import XCTest
@testable import WTRLVehicle
@testable import WTRLGarage
@testable import WTRLCareer
final class Rev35FlagshipOrganismEndgameTests:XCTestCase {
 func testAllFlagshipsHaveDeepAuthoredServiceOrganisms(){ XCTAssertEqual(FlagshipMechanicalOrganismAuthorityRev35.organisms.count,15); for o in FlagshipMechanicalOrganismAuthorityRev35.organisms { XCTAssertGreaterThanOrEqual(o.fasteners.count,22,o.id);XCTAssertGreaterThanOrEqual(o.routes.count,3,o.id);XCTAssertEqual(o.liftPoints.count,4,o.id);XCTAssertGreaterThanOrEqual(o.engineExtraction.count,6,o.id);XCTAssertGreaterThanOrEqual(o.transmissionExtraction.count,5,o.id);XCTAssertFalse(o.finalVerification.isEmpty) } }
 func testApexHasRearTransaxleDrySumpAndActiveAeroServiceRoutes(){ let o=FlagshipMechanicalOrganismAuthorityRev35.organism(SecretApexVehicleRev34.platformId)!; XCTAssertTrue(o.architecture.contains("rear DCT")); XCTAssertTrue(o.routes.contains{$0.kind == .drySump}); XCTAssertTrue(o.connectors.contains{$0.hostNodeId.contains("aero")}); XCTAssertTrue(o.transmissionExtraction.last!.waypoint.z < 0) }
 func testExtractionDependencyOrderIsEnforced(){ let o=FlagshipMechanicalOrganismAuthorityRev35.organism("hero_1968_king")!;var x=FlagshipServiceExecutionRev35(organismId:o.id);XCTAssertFalse(FlagshipServiceExecutionAuthorityRev35.perform(step:o.engineExtraction[2],execution:&x));for s in o.engineExtraction {XCTAssertTrue(FlagshipServiceExecutionAuthorityRev35.perform(step:s,execution:&x))};XCTAssertTrue(FlagshipServiceExecutionAuthorityRev35.verifyFinal(o,execution:x).isEmpty) }
 func testExactServiceSpecificationsRemainResearchGated(){ for o in FlagshipMechanicalOrganismAuthorityRev35.organisms { XCTAssertTrue(o.fasteners.allSatisfy{$0.researchGated && $0.torqueNm == nil}); XCTAssertTrue(o.fluids.allSatisfy{$0.exactCapacityResearchGated}) } }
 func testApexCampaignRequiresEarnedEvidence(){ var p=SecretVehicleProgressRev34();p.state = .claimed;var c=ApexEndgameCampaignRev35();XCTAssertEqual(ApexEndgameCampaignAuthorityRev35.advance(secretProgress:p,campaign:&c),.dynoQualification);c.evidence.dynoStable=true;c.evidence.dynoNoAbort=true;XCTAssertEqual(ApexEndgameCampaignAuthorityRev35.advance(secretProgress:p,campaign:&c),.provingTrial);c.evidence.provingCompleted=true;c.evidence.provingClean=true;c.evidence.telemetryIntegrity01=0.98;XCTAssertEqual(ApexEndgameCampaignAuthorityRev35.advance(secretProgress:p,campaign:&c),.forensicTeardown);c.evidence.teardownCompleted=true;c.evidence.wearFindingsResolved=true;c.evidence.fluidInspectionPassed=true;c.evidence.fastenerAuditPassed=true;XCTAssertEqual(ApexEndgameCampaignAuthorityRev35.advance(secretProgress:p,campaign:&c),.finalCertification);c.evidence.finalVerificationPassed=true;XCTAssertEqual(ApexEndgameCampaignAuthorityRev35.advance(secretProgress:p,campaign:&c),.certified);XCTAssertNotNil(c.certificationId) }
 func testUnclaimedSecretVehicleCannotEnterCampaign(){ let p=SecretVehicleProgressRev34();var c=ApexEndgameCampaignRev35();XCTAssertEqual(ApexEndgameCampaignAuthorityRev35.advance(secretProgress:p,campaign:&c),.locked) }
}
