import XCTest
@testable import WTRLCareer
@testable import WTRLVehicle
@testable import WTRLGarage
final class Rev37AcquisitionEcosystemTests:XCTestCase {
 func testAll186CanEnterAcquisitionEcosystem(){ for e in CompleteVehicleCatalogRev36.entries where e.catalogClass != .secretEndgame { XCTAssertNotNil(AcquisitionEcosystemRev37.listing(platform:e,modelYear:1964,channel:.usedDealer,careerYear:2026)) }; XCTAssertEqual(CompleteVehicleCatalogRev36.playerFacingCount,186) }
 func testFutureCarsCannotAppear(){ let e=CompleteVehicleCatalogRev36.entries[0]; XCTAssertNil(AcquisitionEcosystemRev37.listing(platform:e,modelYear:2026,channel:.usedDealer,careerYear:1970)) }
 func testSecretOnlyUsesEngineeringProgram(){ let e=CompleteVehicleCatalogRev36.entries.first{$0.catalogClass == .secretEndgame}!; XCTAssertNil(AcquisitionEcosystemRev37.listing(platform:e,modelYear:2025,channel:.auction,careerYear:2026)); XCTAssertNotNil(AcquisitionEcosystemRev37.listing(platform:e,modelYear:2025,channel:.secretEngineeringProgram,careerYear:2026)) }
 func testBarnDiscoveryCanHideWrongEngineAndPeriodGearbox(){ let e=CompleteVehicleCatalogRev36.entries.first{$0.catalogClass != .secretEndgame}!; let l=AcquisitionEcosystemRev37.listing(platform:e,modelYear:1968,channel:.barnFind,careerYear:1986,serial:2)!; XCTAssertEqual(l.installedParts.count,2); XCTAssertTrue(l.installedParts.contains{$0.slot=="engine.longblock" && !$0.periodCorrectForVehicle}); XCTAssertTrue(l.installedParts.contains{$0.slot=="transmission.case" && $0.specificationId=="tx_toploader4"}); XCTAssertTrue(l.discoveries.allSatisfy{!$0.revealed}); XCTAssertTrue(AcquisitionEcosystemRev37.inspect(l).discoveries.allSatisfy{$0.revealed}) }
 func testPurchaseCreatesDurableDiscoveredComponents()throws{ let e=CompleteVehicleCatalogRev36.entries.first{$0.catalogClass != .secretEndgame}!; let l=AcquisitionEcosystemRev37.listing(platform:e,modelYear:1968,channel:.projectShell,careerYear:2026,serial:4)!; var c=CareerState(); c.acquisitionMarket.careerYear=2026; c.cashCents=99_000_000; var g=GarageState(); let id=try AcquisitionEcosystemRev37.purchase(l,career:&c,garage:&g); XCTAssertEqual(g.vehicles.first{$0.id==id}?.installations.count,2); XCTAssertEqual(g.components.count,2); XCTAssertTrue(c.acquisitionMarket.acquiredListingIDs.contains(l.id)) }
 func testCareerBackwardDecodeDefaultsMarket()throws{ let data="{\"cashCents\":2500000,\"reputation01\":0,\"evidence\":[]}".data(using:.utf8)!; let c=try JSONDecoder().decode(CareerState.self,from:data); XCTAssertEqual(c.acquisitionMarket.careerYear,1964) }
 func test2026MarketCoversEveryCatalogEntryWhenEndgameReached(){ let m=AcquisitionEcosystemRev37.market(context:.init(careerYear:2026,reputation01:1,highestTierReached:true)); XCTAssertEqual(Set(m.map(\.platformId)),Set(CompleteVehicleCatalogRev36.entries.map(\.id))) }
 func test1970MarketContainsNoFutureDatedCars(){ let m=AcquisitionEcosystemRev37.market(context:.init(careerYear:1970,reputation01:0.2)); XCTAssertTrue(m.allSatisfy{$0.modelYear <= 1970}); XCTAssertFalse(m.isEmpty) }
}
