import XCTest
import WTRLVehicle
import WTRLRendering
final class Rev31DeepAssemblyRealityIdentityTests:XCTestCase {
 func testAll153VehiclesHaveGenerationSpecificDeepAssemblies(){ XCTAssertEqual(HeritageLineageEngineeringRev29.allVehicles.count,153); for v in HeritageLineageEngineeringRev29.allVehicles { let a=GenerationSpecificDeepAssemblyAuthorityRev31.assembly(for:v); XCTAssertTrue(a.validationIssues().isEmpty,"\(v.id): \(a.validationIssues())") } }
 func testArchitecturesProduceDifferentPhysicalHardware(){ let all=HeritageLineageEngineeringRev29.allVehicles; let leaf=all.first{$0.rearKinematics.lowercased().contains("leaf")}!; let independent=all.first{$0.rearKinematics.lowercased().contains("multi-link") || $0.rearKinematics.lowercased().contains("independent")}!; XCTAssertNotEqual(Set(GenerationSpecificDeepAssemblyAuthorityRev31.assembly(for:leaf).nodes.map(\.id)),Set(GenerationSpecificDeepAssemblyAuthorityRev31.assembly(for:independent).nodes.map(\.id))) }
 func testRealityKitManifestUsesOnePhysicalIdentity(){ let v=HeritageLineageEngineeringRev29.allVehicles[0]; let a=GenerationSpecificDeepAssemblyAuthorityRev31.assembly(for:v); let m=RealityKitPhysicalIdentityAuthorityRev31.manifest(for:a); XCTAssertEqual(m.bindings.count,a.nodes.count); XCTAssertTrue(m.bindings.allSatisfy{$0.assemblyNodeId==$0.physicsBindingId && $0.assemblyNodeId==$0.renderEntityName}) }
 func testRealityKitManifestDetectsMissingMeshEntities(){ let v=HeritageLineageEngineeringRev29.allVehicles[0]; let m=RealityKitPhysicalIdentityAuthorityRev31.manifest(for:GenerationSpecificDeepAssemblyAuthorityRev31.assembly(for:v)); XCTAssertEqual(RealityKitPhysicalIdentityAuthorityRev31.validationIssues(m,availableEntityNames:m.expectedEntityNames).count,0); XCTAssertFalse(RealityKitPhysicalIdentityAuthorityRev31.validationIssues(m,availableEntityNames:[]).isEmpty) }
 func testForcedInductionGenerationsGetSpecificHardware(){ let cars=HeritageLineageEngineeringRev29.allVehicles.filter{$0.induction.lowercased().contains("turbo") || $0.induction.lowercased().contains("super")}; XCTAssertFalse(cars.isEmpty); for v in cars { let ids=Set(GenerationSpecificDeepAssemblyAuthorityRev31.assembly(for:v).nodes.map(\.id)); XCTAssertTrue(ids.contains("induction.turbo") || ids.contains("induction.supercharger") || ids.contains("induction.forced"),v.id) } }
}
