import XCTest
import WTRLVehicle
import WTRLGarage
import WTRLRendering
final class Rev32DurableFordRealityTests:XCTestCase {
 func testFordContinuumHasThreeNineVehicleSimulationTracks(){let p=FordContinuumSimulationAuthorityRev32.all;XCTAssertEqual(p.count,27);XCTAssertEqual(p.filter{$0.track == .heavyIronPursuit}.count,9);XCTAssertEqual(p.filter{$0.track == .homologationRally}.count,9);XCTAssertEqual(p.filter{$0.track == .aerospaceEndurance}.count,9)}
 func testFordTracksHaveDistinctEngineeringPriorities(){let p=FordContinuumSimulationAuthorityRev32.all;let sets=Dictionary(grouping:p,by:\.track).mapValues{Set($0.flatMap(\.priorityDomains))};XCTAssertEqual(sets.count,3);XCTAssertNotEqual(sets[.heavyIronPursuit],sets[.homologationRally]);XCTAssertNotEqual(sets[.homologationRally],sets[.aerospaceEndurance])}
 func testEveryHeritageVehicleSeedsDurableUniqueComponentInstances(){for v in HeritageLineageEngineeringRev29.allVehicles {let a=DurableComponentIdentityAuthorityRev32.seed(vehicleInstanceId:"VIN-\(v.id)",platform:v);XCTAssertTrue(DurableComponentIdentityAuthorityRev32.validate(a).isEmpty,v.id);XCTAssertGreaterThanOrEqual(a.components.count,34)}}
 func testReplacementChangesPhysicalIdentityButKeepsAssemblyAndRenderIdentity(){let v=HeritageLineageEngineeringRev29.allVehicles[0];let a=DurableComponentIdentityAuthorityRev32.seed(vehicleInstanceId:"V1",platform:v);let old=a.components["hub.fl"]!;let n=DurableComponentIdentityAuthorityRev32.replacement(for:old,newSerial:"NEW-HUB");XCTAssertNotEqual(old.componentInstanceId,n.componentInstanceId);XCTAssertEqual(old.assemblyNodeId,n.assemblyNodeId);XCTAssertEqual(old.renderEntityName,n.renderEntityName);XCTAssertFalse(n.torqueVerified)}
 func testConnectedPartCannotExtractUntilInterfacesDisconnected(){let v=HeritageLineageEngineeringRev29.allVehicles[0];var s=ServiceConnectionAuthorityRev32.seed(vehicleInstanceId:"V1",platform:v);let slot="cooling.pump";XCTAssertFalse(ServiceConnectionAuthorityRev32.canExtract(slot:slot,state:s));for (id,c) in s.connections where c.hostComponentInstanceId==s.assembly.components[slot]?.componentInstanceId || c.guestComponentInstanceId==s.assembly.components[slot]?.componentInstanceId {ServiceConnectionAuthorityRev32.disconnect(id,state:&s)};XCTAssertTrue(ServiceConnectionAuthorityRev32.canExtract(slot:slot,state:s))}
 func testRenderCommandCarriesComponentAndAssemblyIdentity(){let v=HeritageLineageEngineeringRev29.allVehicles[0];let c=DurableComponentIdentityAuthorityRev32.seed(vehicleInstanceId:"V1",platform:v).components["hub.fl"]!;let r=RealityKitServiceStateAuthorityRev32.command(for:c);XCTAssertEqual(r.componentInstanceId,c.componentInstanceId);XCTAssertEqual(r.entityName,"hub.fl");XCTAssertEqual(r.parentAnchor,"vehicle.root")}
}
