import XCTest
@testable import WTRLVehicle
@testable import WTRLGarage
@testable import WTRLRendering
final class Rev33ProductionServiceMustangTests:XCTestCase {
 func testMustangReferenceLineageIsResearchGated(){ XCTAssertEqual(MustangHeritageRev33.vehicles.count,14); XCTAssertTrue(MustangHeritageRev33.vehicles.allSatisfy{$0.sourceStatus == .researchPending && !$0.researchGatedClaims.isEmpty}) }
 func testMustangArchitecturesSpanClassicTurboIRSSuperchargedAndAero(){ let v=MustangHeritageRev33.vehicles; XCTAssertTrue(v.contains{$0.fuelMetering.lowercased().contains("carb")}); XCTAssertTrue(v.contains{$0.induction.lowercased().contains("turbo")}); XCTAssertTrue(v.contains{$0.rearKinematics.lowercased().contains("independent") || $0.rearKinematics.lowercased().contains("multi-link")}); XCTAssertTrue(v.contains{$0.dynamicMechanisms.joined().lowercased().contains("aero")}) }
 func testEveryHeritageAndMustangVehicleGetsProductionServicePlans(){ for v in HeritageLineageEngineeringRev29.allVehicles + MustangHeritageRev33.vehicles { let graph=GenerationSpecificDeepAssemblyAuthorityRev31.assembly(for:v); let plans=ProductionServicePlanAuthorityRev33.plans(for:v); XCTAssertEqual(graph.nodes.count,plans.count); XCTAssertTrue(plans.allSatisfy{!$0.interfaces.isEmpty}) } }
 func testExtractionBlockedUntilInterfacesResolved(){ let v=MustangHeritageRev33.vehicles[10]; var r=ProductionServiceRuntimeAuthorityRev33.seed(vehicleInstanceId:"car1",platform:v); let slot="cooling.pump"; XCTAssertFalse(ProductionServiceRuntimeAuthorityRev33.remove(slot:slot,runtime:&r)); guard let p=r.plans[slot] else{return XCTFail()}; for x in p.interfaces { let s:ServiceInterfaceStateRev33; switch x.role {case .fastenerGroup:s = .loosened;case .electricalConnector,.hoseClamp,.fluidJoint:s = .disconnected;case .supportPoint:s = .supported;case .extractionClearance,.bondedJoint:s = .cleared}; ProductionServiceRuntimeAuthorityRev33.setInterface(slot:slot,interfaceId:x.id,to:s,runtime:&r) }; XCTAssertTrue(ProductionServiceRuntimeAuthorityRev33.remove(slot:slot,runtime:&r)); XCTAssertEqual(r.removedInventory.count,1) }
 func testReplacementGetsNewDurableIdentityAndNeedsVerification(){ let v=MustangHeritageRev33.vehicles[1]; var r=ProductionServiceRuntimeAuthorityRev33.seed(vehicleInstanceId:"king",platform:v); let old=r.state.assembly.components["engine.longblock"]!.componentInstanceId; XCTAssertTrue(ProductionServiceRuntimeAuthorityRev33.installReplacement(slot:"engine.longblock",serial:"NEW-ENGINE-001",runtime:&r)); let n=r.state.assembly.components["engine.longblock"]!; XCTAssertNotEqual(old,n.componentInstanceId); XCTAssertFalse(n.torqueVerified); XCTAssertFalse(n.calibrationVerified) }
 func testRealityServiceCommandPreservesComponentAndEntityIdentity(){ let v=MustangHeritageRev33.vehicles[10]; let r=ProductionServiceRuntimeAuthorityRev33.seed(vehicleInstanceId:"gt500",platform:v); let c=r.state.assembly.components["cooling.pump"]!, p=r.plans["cooling.pump"]!; let x=RealityServiceTransformAuthorityRev33.transform(component:c,plan:p); XCTAssertEqual(x.componentInstanceId,c.componentInstanceId); XCTAssertEqual(x.entityName,c.assemblyNodeId); XCTAssertEqual(x.parentAnchor,"garage.service_stage") }
}
