import XCTest
@testable import WTRLVehicle
@testable import WTRLGarage
@testable import WTRLCareer
@testable import WTRLRendering
final class Rev34SecretApexPhysicalInteractionTests:XCTestCase {
 func testSecretVehicleHasDeepUniqueAssembly(){let a=SecretApexDeepAssemblyAuthorityRev34.assembly(); XCTAssertTrue(a.validationIssues().isEmpty); for id in ["engine.dry_sump.pump","driveline.carbon_torque_shaft","transmission.rear_transaxle","suspension.rear.inboard_damper.left","aero.rear.active_wing"]{XCTAssertNotNil(a.nodes.first{$0.id==id})}; XCTAssertGreaterThan(a.nodes.count,50)}
 func testSecretVehicleIsHiddenBelowElite(){var p=SecretVehicleProgressRev34(); let r=SecretVehicleUnlockAuthorityRev34.evaluate(tier:.professional,ratings:.init(),progress:p); XCTAssertEqual(r.state,.hidden); XCTAssertNil(SecretVehicleUnlockAuthorityRev34.claim(tier:.professional,ratings:.init(),progress:&p))}
 func testEliteUnlockRequiresFinaleReputationAndTrials(){var p=SecretVehicleProgressRev34(); var d=DriverRatings(); d.reputation=0.95; var e=SecretVehicleUnlockAuthorityRev34.evaluate(tier:.elite,ratings:d,progress:p); XCTAssertEqual(e.state,.revealed); p.eliteChampionshipWins=1;p.cleanEliteFinale=true;p.apexTrialsCompleted=SecretVehicleUnlockAuthorityRev34.requiredTrials;e=SecretVehicleUnlockAuthorityRev34.evaluate(tier:.elite,ratings:d,progress:p);XCTAssertEqual(e.state,.unlocked);let v=SecretVehicleUnlockAuthorityRev34.claim(tier:.elite,ratings:d,progress:&p);XCTAssertEqual(v?.platformId,SecretApexVehicleRev34.platformId);XCTAssertEqual(p.state,.claimed);XCTAssertNil(SecretVehicleUnlockAuthorityRev34.claim(tier:.elite,ratings:d,progress:&p))}
 func testPhysicalInteractionCreatesFastenersConnectorsSupportAndPaths(){let v=SecretApexVehicleRev34.referenceProfile;let r=PhysicalInteractionAuthorityRev34.seed(vehicleInstanceId:"apex",platform:v);XCTAssertFalse(r.fasteners.isEmpty);XCTAssertFalse(r.extractionPaths.isEmpty);XCTAssertNotNil(r.supports["engine.longblock"]);XCTAssertNotNil(r.connectors["cooling.pump"])}
 func testConnectorRequiresLockSequence(){let v=SecretApexVehicleRev34.referenceProfile;var r=PhysicalInteractionAuthorityRev34.seed(vehicleInstanceId:"apex",platform:v);guard let id=r.connectors["cooling.pump"]?.first?.id else{return XCTFail()};XCTAssertFalse(PhysicalInteractionAuthorityRev34.releaseConnector(slot:"cooling.pump",id:id,runtime:&r));XCTAssertFalse(PhysicalInteractionAuthorityRev34.releaseConnector(slot:"cooling.pump",id:id,runtime:&r));XCTAssertTrue(PhysicalInteractionAuthorityRev34.releaseConnector(slot:"cooling.pump",id:id,runtime:&r))}
 func testDrainPanDeterminesCaptureVersusSpill(){let v=SecretApexVehicleRev34.referenceProfile;var r=PhysicalInteractionAuthorityRev34.seed(vehicleInstanceId:"apex",platform:v);guard let slot=r.fluids.keys.first else{return XCTFail()};PhysicalInteractionAuthorityRev34.drain(slot:slot,liters:1,runtime:&r);XCTAssertEqual(r.fluids[slot]?.spilledLiters,1);r.fluids[slot]?.drainPanPresent=true;PhysicalInteractionAuthorityRev34.drain(slot:slot,liters:2,runtime:&r);XCTAssertEqual(r.fluids[slot]?.capturedLiters,2)}
 func testRealityToolContactUsesSamePhysicalIdentity(){let v=SecretApexVehicleRev34.referenceProfile;let r=PhysicalInteractionAuthorityRev34.seed(vehicleInstanceId:"apex",platform:v);guard let c=r.service.state.assembly.components["engine.longblock"],let f=r.fasteners["engine.longblock"]?.first else{return XCTFail()};let contact=RealityToolContactRev34(toolEntityName:"tool.torque",targetFastenerId:f.id,assemblyNodeId:f.assemblyNodeId,contactValid:true);XCTAssertTrue(RealityPhysicalInteractionIdentityRev34.validate(component:c,contact:contact))}
}
