import Foundation

public enum ComponentServiceLifecycleRev32:String,Codable,Hashable,Sendable { case installed, loosened, disconnected, supported, extracting, removed, staged, inspected, repaired, rebuilt, replacementReady, condemned }
public struct InstalledComponentBindingRev32:Codable,Hashable,Sendable,Identifiable {
 public var id:String { componentInstanceId }; public var componentInstanceId:String; public var vehicleInstanceId:String; public var assemblyNodeId:String; public var specificationId:String; public var lifecycle:ComponentServiceLifecycleRev32; public var condition01:Double; public var wear01:Double; public var damage01:Double; public var deformationMm:Double; public var temperatureC:Double; public var torqueVerified:Bool; public var calibrationVerified:Bool; public var renderEntityName:String; public var history:[String]
 public init(componentInstanceId:String=UUID().uuidString,vehicleInstanceId:String,assemblyNodeId:String,specificationId:String,lifecycle:ComponentServiceLifecycleRev32 = .installed,condition01:Double=1,wear01:Double=0,damage01:Double=0,deformationMm:Double=0,temperatureC:Double=20,torqueVerified:Bool=false,calibrationVerified:Bool=false,renderEntityName:String?=nil,history:[String]=[]){self.componentInstanceId=componentInstanceId;self.vehicleInstanceId=vehicleInstanceId;self.assemblyNodeId=assemblyNodeId;self.specificationId=specificationId;self.lifecycle=lifecycle;self.condition01=condition01;self.wear01=wear01;self.damage01=damage01;self.deformationMm=deformationMm;self.temperatureC=temperatureC;self.torqueVerified=torqueVerified;self.calibrationVerified=calibrationVerified;self.renderEntityName=renderEntityName ?? assemblyNodeId;self.history=history}
}
public struct DurableVehicleAssemblyRev32:Codable,Hashable,Sendable { public var vehicleInstanceId:String; public var platformId:String; public var components:[String:InstalledComponentBindingRev32] }
public enum DurableComponentIdentityAuthorityRev32 {
 public static func seed(vehicleInstanceId:String,platform:HeritageVehicleEngineeringProfile)->DurableVehicleAssemblyRev32 { let graph=GenerationSpecificDeepAssemblyAuthorityRev31.assembly(for:platform); return .init(vehicleInstanceId:vehicleInstanceId,platformId:platform.id,components:Dictionary(uniqueKeysWithValues:graph.nodes.map{ n in let c=InstalledComponentBindingRev32(vehicleInstanceId:vehicleInstanceId,assemblyNodeId:n.id,specificationId:"spec.\(platform.id).\(n.id)"); return (n.id,c)})) }
 public static func replacement(for old:InstalledComponentBindingRev32,newSerial:String)->InstalledComponentBindingRev32 { .init(componentInstanceId:newSerial,vehicleInstanceId:old.vehicleInstanceId,assemblyNodeId:old.assemblyNodeId,specificationId:old.specificationId,lifecycle:.replacementReady,condition01:1,wear01:0,damage01:0,deformationMm:0,temperatureC:20,torqueVerified:false,calibrationVerified:false,renderEntityName:old.renderEntityName,history:old.history+["replaced component \(old.componentInstanceId)"]) }
 public static func validate(_ a:DurableVehicleAssemblyRev32)->[String] { var x:[String]=[]; let ids=a.components.values.map(\.componentInstanceId); if Set(ids).count != ids.count{x.append("duplicate component instance identity")}; for (slot,c) in a.components {if slot != c.assemblyNodeId{x.append("slot identity mismatch \(slot)")}; if c.renderEntityName != slot{x.append("render identity split \(slot)")}}; return x }
}
