import Foundation
import WTRLCore

public enum FlagshipServicePoseRev35:String,Codable,Hashable,Sendable { case curb, twoPostLift, fourPostAlignmentRack, wheelFreeLift, engineCrane, transmissionJack, componentBench, dynoCell, provingGround }
public enum ServiceLineKindRev35:String,Codable,Hashable,Sendable { case fuel, coolant, oil, brake, clutch, vacuum, boost, electrical, hydraulic, transaxleOil, drySump }
public struct AuthoredFastenerRev35:Codable,Hashable,Sendable,Identifiable { public var id:String; public var hostNodeId:String; public var position:Vector3D; public var drive:String; public var accessAfter:[String]; public var torqueNm:Double?; public var researchGated:Bool }
public struct AuthoredRoutePointRev35:Codable,Hashable,Sendable { public var position:Vector3D; public var clampOrConnectorId:String? }
public struct AuthoredServiceRouteRev35:Codable,Hashable,Sendable,Identifiable { public var id:String; public var kind:ServiceLineKindRev35; public var fromNode:String; public var toNode:String; public var points:[AuthoredRoutePointRev35]; public var drainBeforeDisconnect:Bool }
public struct AuthoredConnectorRev35:Codable,Hashable,Sendable,Identifiable { public var id:String; public var hostNodeId:String; public var position:Vector3D; public var lockStages:Int; public var accessAfter:[String] }
public struct AuthoredLiftPointRev35:Codable,Hashable,Sendable,Identifiable { public var id:String; public var position:Vector3D; public var fixture:String; public var researchGatedCapacity:Bool }
public struct AuthoredPanelRev35:Codable,Hashable,Sendable,Identifiable { public var id:String; public var fastenerIds:[String]; public var accessAfter:[String]; public var removalPose:Vector3D }
public struct AuthoredExtractionStepRev35:Codable,Hashable,Sendable,Identifiable { public var id:String; public var instruction:String; public var requires:[String]; public var pose:FlagshipServicePoseRev35; public var waypoint:Vector3D }
public struct BenchOperationRev35:Codable,Hashable,Sendable,Identifiable { public var id:String; public var componentNodeId:String; public var operation:String; public var prerequisites:[String]; public var verification:String; public var researchGatedSpecification:Bool }
public struct FluidProcedureRev35:Codable,Hashable,Sendable,Identifiable { public var id:String; public var family:ServiceLineKindRev35; public var drainOrder:[String]; public var refillOrder:[String]; public var bleedOrPrime:[String]; public var verification:[String]; public var exactCapacityResearchGated:Bool }
public struct FlagshipMechanicalOrganismRev35:Codable,Hashable,Sendable,Identifiable {
 public var id:String; public var displayName:String; public var platformId:String; public var architecture:String
 public var fasteners:[AuthoredFastenerRev35]; public var routes:[AuthoredServiceRouteRev35]; public var connectors:[AuthoredConnectorRev35]; public var liftPoints:[AuthoredLiftPointRev35]; public var panels:[AuthoredPanelRev35]; public var servicePoses:[FlagshipServicePoseRev35]; public var engineExtraction:[AuthoredExtractionStepRev35]; public var transmissionExtraction:[AuthoredExtractionStepRev35]; public var benchOperations:[BenchOperationRev35]; public var fluids:[FluidProcedureRev35]; public var finalVerification:[String]; public var researchGates:[String]
}

public enum FlagshipMechanicalOrganismAuthorityRev35 {
 private static func f(_ host:String,_ n:Int,_ z:Double=0)->[AuthoredFastenerRev35] { (0..<n).map { i in let x=(i%2==0 ? -0.18:0.18); let y=Double(i/2)*0.12-0.12; return .init(id:"fastener.\(host).\(i+1)",hostNodeId:host,position:Vector3D(x,y,z),drive:"socket/torque tool",accessAfter:[],torqueNm:nil,researchGated:true) } }
 private static func route(_ id:String,_ kind:ServiceLineKindRev35,_ from:String,_ to:String,_ drain:Bool=true)->AuthoredServiceRouteRev35 { .init(id:id,kind:kind,fromNode:from,toNode:to,points:[.init(position:Vector3D(-0.2,0,0),clampOrConnectorId:"\(id).clamp.1"),.init(position:Vector3D(0,0.18,0.05),clampOrConnectorId:"\(id).clamp.2"),.init(position:Vector3D(0.2,0.28,0),clampOrConnectorId:nil)],drainBeforeDisconnect:drain) }
 private static func organism(_ id:String,_ name:String,_ architecture:String,_ modern:Bool,_ rearTransaxle:Bool=false,_ drySump:Bool=false,_ activeAero:Bool=false)->FlagshipMechanicalOrganismRev35 {
  var fast=f("hood",4)+f("engine.longblock",8)+f(rearTransaxle ? "transmission.rear_transaxle":"transmission.case",8)+f("cooling.radiator",4)+f("differential.case",6)
  if modern { fast += f("body.front_undertray",8)+f("body.rear_undertray",8) }
  var routes=[route("route.coolant.main",.coolant,"engine.longblock","cooling.radiator"),route("route.fuel.feed",.fuel,"fuel.tank","engine.longblock"),route("route.brake.front",.brake,"brake.master","brake.front")]
  if modern { routes += [route("route.electrical.engine",.electrical,"electrical.main_harness","engine.longblock",false),route("route.charge",.boost,"induction.primary","cooling.charge",false)] }
  if drySump { routes += [route("route.drysump.scavenge",.drySump,"engine.dry_sump.pump","engine.dry_sump.tank"),route("route.drysump.pressure",.oil,"engine.dry_sump.tank","engine.longblock")] }
  var connectors:[AuthoredConnectorRev35] = modern ? [.init(id:"connector.engine.main",hostNodeId:"engine.longblock",position:Vector3D(0.25,0.1,0.2),lockStages:3,accessAfter:["hood"]),.init(id:"connector.transmission.main",hostNodeId:rearTransaxle ? "transmission.rear_transaxle":"transmission.case",position:Vector3D(-0.2,-0.1,0.1),lockStages:3,accessAfter:["body.rear_undertray"])] : [.init(id:"connector.starter",hostNodeId:"engine.longblock",position:Vector3D(0.2,-0.2,-0.1),lockStages:1,accessAfter:["hood"])]
  if activeAero { connectors.append(.init(id:"connector.aero.rear",hostNodeId:"aero.rear.active_wing",position:Vector3D(0,0.15,0),lockStages:3,accessAfter:["body.rear_undertray"])) }
  let panels:[AuthoredPanelRev35] = [.init(id:"hood",fastenerIds:f("hood",4).map(\.id),accessAfter:[],removalPose:Vector3D(0,0.8,0.25))] + (modern ? [.init(id:"body.front_undertray",fastenerIds:f("body.front_undertray",8).map(\.id),accessAfter:["lift.vehicle"],removalPose:Vector3D(0,-0.45,0)),.init(id:"body.rear_undertray",fastenerIds:f("body.rear_undertray",8).map(\.id),accessAfter:["lift.vehicle"],removalPose:Vector3D(0,-0.45,0))] : [])
  let engine:[AuthoredExtractionStepRev35] = [.init(id:"engine.1",instruction:"Raise vehicle and establish verified lifting/support points",requires:[],pose:.twoPostLift,waypoint:.zero),.init(id:"engine.2",instruction:"Drain required fluids into identified containment",requires:["engine.1"],pose:.twoPostLift,waypoint:.zero),.init(id:"engine.3",instruction:"Remove access panels and disconnect routed lines/connectors",requires:["engine.2"],pose:.twoPostLift,waypoint:Vector3D(0,0.1,0)),.init(id:"engine.4",instruction:"Support powertrain before releasing mounts",requires:["engine.3"],pose:.engineCrane,waypoint:Vector3D(0,0.2,0)),.init(id:"engine.5",instruction:"Extract along collision-cleared authored path",requires:["engine.4"],pose:.engineCrane,waypoint:Vector3D(0,0.85,0.25)),.init(id:"engine.6",instruction:"Transfer durable component instance to engine stand",requires:["engine.5"],pose:.componentBench,waypoint:Vector3D(1.2,0.7,0))]
  let trans:[AuthoredExtractionStepRev35] = [.init(id:"trans.1",instruction:"Remove underbody access and drain lubricant where required",requires:[],pose:.twoPostLift,waypoint:.zero),.init(id:"trans.2",instruction:"Disconnect harness, cooler lines and driveline interfaces",requires:["trans.1"],pose:.twoPostLift,waypoint:Vector3D(0,-0.1,0)),.init(id:"trans.3",instruction:"Engage transmission/transaxle support fixture",requires:["trans.2"],pose:.transmissionJack,waypoint:Vector3D(0,-0.25,0)),.init(id:"trans.4",instruction:"Release researched mount/retention sequence",requires:["trans.3"],pose:.transmissionJack,waypoint:Vector3D(0,-0.35,0)),.init(id:"trans.5",instruction:"Extract to service stage preserving component identity",requires:["trans.4"],pose:.transmissionJack,waypoint:Vector3D(0,-0.55,rearTransaxle ? -0.8:0.25))]
  let bench:[BenchOperationRev35] = [.init(id:"bench.engine.inspect",componentNodeId:"engine.longblock",operation:"clean, inspect, measure and photograph evidence before disassembly",prerequisites:["engine.6"],verification:"evidence record complete",researchGatedSpecification:false),.init(id:"bench.engine.rebuild",componentNodeId:"engine.longblock",operation:"teardown in dependency order; measure wear; replace/recondition serviceable subcomponents; reassemble",prerequisites:["bench.engine.inspect"],verification:"rotation, sealing, lubrication and timing proof",researchGatedSpecification:true),.init(id:"bench.transaxle",componentNodeId:rearTransaxle ? "transmission.rear_transaxle":"transmission.case",operation:"inspect fluid/debris, endplay/backlash/bearing state and actuator/mechatronic evidence",prerequisites:["trans.5"],verification:"cold functional check and leak proof",researchGatedSpecification:true)]
  var fluids:[FluidProcedureRev35] = [.init(id:"fluid.coolant",family:.coolant,drainOrder:["coolant reservoir","radiator low point","engine low points where authored"],refillOrder:["close verified drains","vacuum-fill or controlled fill","heater/aux circuits"],bleedOrPrime:["purge trapped air","cycle pumps/thermostat logic"],verification:["stable level","pressure hold","temperature delta and no hot spots"],exactCapacityResearchGated:true),.init(id:"fluid.brake",family:.brake,drainOrder:["service only opened circuit"],refillOrder:["verified compatible fluid"],bleedOrPrime:["pressure bleed in authored corner order","ABS service bleed when architecture requires"],verification:["firm pedal","no air","pressure hold","road/dyno brake balance"],exactCapacityResearchGated:true)]
  if drySump { fluids.append(.init(id:"fluid.drysump",family:.drySump,drainOrder:["reservoir","scavenge circuit where required"],refillOrder:["reservoir staged fill"],bleedOrPrime:["prime pressure circuit before firing","verify scavenge return"],verification:["cranking pressure","hot pressure","reservoir level after stabilization"],exactCapacityResearchGated:true)) }
  return .init(id:id,displayName:name,platformId:id,architecture:architecture,fasteners:fast,routes:routes,connectors:connectors,liftPoints:[.init(id:"lift.fl",position:Vector3D(-0.7,0,1.0),fixture:"two-post arm",researchGatedCapacity:true),.init(id:"lift.fr",position:Vector3D(0.7,0,1.0),fixture:"two-post arm",researchGatedCapacity:true),.init(id:"lift.rl",position:Vector3D(-0.7,0,-1.0),fixture:"two-post arm",researchGatedCapacity:true),.init(id:"lift.rr",position:Vector3D(0.7,0,-1.0),fixture:"two-post arm",researchGatedCapacity:true)],panels:panels,servicePoses:[.curb,.twoPostLift,.fourPostAlignmentRack,.engineCrane,.transmissionJack,.componentBench,.dynoCell,.provingGround],engineExtraction:engine,transmissionExtraction:trans,benchOperations:bench,fluids:fluids,finalVerification:["all fasteners have provenance and required final torque witness","all connectors locked and secondary locks verified","all fluids leak-free, filled, bled/primed and thermally stable","alignment/steering center verified","dyno or loaded functional proof completed","road/proving telemetry compared with pre-repair evidence","save/reload preserves installed component identities and service history"],researchGates:["exact fastener coordinates require production 3D authoring","exact OEM torque values","exact hose/line routing","exact lift capacities/locations","exact fluid capacities and bleed sequences","proprietary calibration values"])
 }
 public static let organisms:[FlagshipMechanicalOrganismRev35] = [
  organism("hero_1967_original","1967 Crownfire Original","classic carbureted live-axle fastback",false), organism("hero_1968_king","1968 Crownfire King","high-output carbureted classic fastback",false), organism("hero_1970_grand","1970 Crownfire Grand","aero-influenced classic grand tourer",false), organism("hero_2008_rebirth","2008 Crownfire Rebirth","supercharged modern live-axle coupe",true), organism("hero_2011_evolution","2011 Crownfire Evolution","supercharged EPAS performance coupe",true), organism("hero_2014_hammer","2014 Crownfire Hammer","high-speed track coupe",true), organism("hero_2022_apex","2022 Crownfire Apex","supercharged DCT IRS track coupe",true), organism("hero_exp_lab","Crownfire EXP Laboratory","prototype instrumented GT",true), organism("legend_gtx_bloodline_zero","Legend GT-X Bloodline Zero","endgame prototype GT",true),
  organism("ford_endurance_halo_1","GT40 Mk II reference flagship","mid-engine endurance transaxle",false), organism("ford_homologation_8","Focus RS Mk3 reference flagship","turbo AWD active-rear-coupling hatch",true), organism("ford_endurance_halo_7","Ford GT reference flagship","mid-engine supercharged transaxle",true), organism("ford_endurance_halo_8","Ford GT GTE reference flagship","carbon endurance aero prototype",true,false,false,true), organism("ford_heavy_iron_9","Police Interceptor reference flagship","twin-turbo AWD pursuit utility",true),
  organism(SecretApexVehicleRev34.platformId,"Apex Revenant","front-mid supercharged dry-sump V8 / carbon torque shaft / rear DCT transaxle / inboard rear suspension / active aero",true,true,true,true)
 ]
 public static func organism(_ id:String)->FlagshipMechanicalOrganismRev35? { organisms.first{$0.id==id} }
}
