import Foundation
public enum HeritageAssemblySubsystemRev30:String,Codable,Sendable { case structure,body,steering,suspension,brakes,wheelsTires,engine,induction,fuel,cooling,transmission,driveline,differential,electrical,aero }
public struct HeritageAssemblyNodeRev30:Codable,Hashable,Sendable,Identifiable { public var id:String; public var name:String; public var subsystem:HeritageAssemblySubsystemRev30; public var parentId:String?; public var removalPrerequisites:[String]; public var visualBindingId:String; public var physicsBindingId:String; public var failureModes:[String]; public var researchGates:[String] }
public struct HeritageAssemblyGraphRev30:Codable,Hashable,Sendable { public var vehicleId:String; public var nodes:[HeritageAssemblyNodeRev30]; public func node(_ id:String)->HeritageAssemblyNodeRev30?{nodes.first{$0.id==id}}; public func validationIssues()->[String]{ let ids=Set(nodes.map(\.id)); var out:[String]=[]; if ids.count != nodes.count {out.append("duplicate ids")}; for n in nodes {if let p=n.parentId,!ids.contains(p){out.append("missing parent \(p)")}; for r in n.removalPrerequisites where !ids.contains(r){out.append("missing prerequisite \(r)")}; if n.visualBindingId != n.physicsBindingId {out.append("identity split \(n.id)")}}; return out } }
public enum HeritageAssemblyAuthorityRev30 {
 public static func graph(for v:HeritageVehicleEngineeringProfile)->HeritageAssemblyGraphRev30 {
  func n(_ id:String,_ name:String,_ s:HeritageAssemblySubsystemRev30,_ p:String?=nil,_ r:[String]=[],_ f:[String]=[])->HeritageAssemblyNodeRev30{.init(id:id,name:name,subsystem:s,parentId:p,removalPrerequisites:r,visualBindingId:id,physicsBindingId:id,failureModes:f,researchGates:["exact OEM geometry","exact OEM fastener/torque data"])}
  let phys=HeritageExecutablePhysicsAuthorityRev30.profile(for:v)
  var a=[n("body.shell","Body shell",.structure,nil,[],["datum shift","fatigue"]),n("engine.longblock","Engine long block",.engine,"body.shell",["hood"],["sealing loss","bearing wear"]),n("hood","Hood",.body,"body.shell",[],["hinge/alignment wear"]),n("cooling.primary","Primary cooling",.cooling,"body.shell",["hood"],["restriction","leak","heat soak"]),n("transmission.case","Transmission",.transmission,"body.shell",["driveshaft.main"],["wear","thermal overload"]),n("driveshaft.main","Primary driveline shaft",.driveline,"transmission.case",[],["runout","joint wear","phasing"]),n("differential.case","Differential",.differential,"body.shell",["driveshaft.main"],["backlash","preload loss","thermal overload"]),n("steering.gear","Steering gear",.steering,"body.shell",[],["free play","assist fault"]),n("suspension.front","Front suspension",.suspension,"body.shell",[],["bushing compliance","damper fade","geometry migration"]),n("suspension.rear","Rear suspension",.suspension,"body.shell",[],["bushing compliance","axle windup","geometry migration"]),n("brake.front","Front brake system",.brakes,"suspension.front",[],["thermal saturation","runout","drag"]),n("brake.rear","Rear brake system",.brakes,"suspension.rear",[],["thermal saturation","drag"]),n("wheel.fl","Front-left wheel/tire",.wheelsTires,"suspension.front",[],["runout","pressure loss"]),n("wheel.fr","Front-right wheel/tire",.wheelsTires,"suspension.front",[],["runout","pressure loss"]),n("wheel.rl","Rear-left wheel/tire",.wheelsTires,"suspension.rear",[],["runout","pressure loss"]),n("wheel.rr","Rear-right wheel/tire",.wheelsTires,"suspension.rear",[],["runout","pressure loss"])]
  switch phys.fuel { case .carbureted: a += [n("fuel.carburetor","Carburetor assembly",.fuel,"engine.longblock",["hood"],["float error","restriction","vacuum leak"]),n("fuel.pump","Fuel pump",.fuel,"engine.longblock",[],["delivery loss"])] ; case .mechanicalInjection: a += [n("fuel.metering","Mechanical fuel metering",.fuel,"engine.longblock",["hood"],["correlation error","restriction"])] ; case .portEFI,.directInjection: a += [n("fuel.rail","Fuel rail/injection",.fuel,"engine.longblock",["hood"],["pressure loss","injector imbalance"]),n("electrical.engine_control","Engine control electrical",.electrical,"body.shell",[],["sensor bias","connector resistance"])] ; case .unknown: break }
  if phys.induction != .naturallyAspirated { a += [n("induction.forced","Forced-induction assembly",.induction,"engine.longblock",["hood"],["boost leak","bearing wear","thermal soak"]),n("cooling.charge","Charge-air cooling",.cooling,"body.shell",["hood"],["pump loss","air entrapment","heat soak"])] }
  if v.dynamicMechanisms.joined(separator:" ").lowercased().contains("aero") || v.displayName.lowercased().contains("gt40") { a += [n("aero.package","Aerodynamic package",.aero,"body.shell",[],["ride-height sensitivity","mount damage"])] }
  if phys.drive == .awd { a += [n("driveline.awd_coupling","AWD coupling",.driveline,"transmission.case",[],["clutch heat","actuator fault"])] }
  return .init(vehicleId:v.id,nodes:a)
 }
}
