import Foundation

public enum EngineeringProvenance:String,Codable,Sendable { case verifiedReference, researchPending, fictionalProductionCalibration }
public enum HeritageCategory:String,Codable,Sendable { case muscle, cruiser, tuner, sports, exotic, halo }
public struct HeritageWorkshopProcedure:Codable,Hashable,Sendable { public var title:String; public var measurementFamily:String; public var researchStatus:EngineeringProvenance }
public struct HeritageVehicleEngineeringProfile:Codable,Hashable,Sendable,Identifiable {
 public var id:String; public var lineageId:String; public var trackId:String?; public var era:Int; public var displayName:String; public var category:HeritageCategory
 public var powertrainArchitecture:String; public var fuelMetering:String; public var induction:String; public var frontKinematics:String; public var rearKinematics:String; public var steering:String
 public var dynamicMechanisms:[String]; public var workshopProcedures:[HeritageWorkshopProcedure]; public var sourceStatus:EngineeringProvenance; public var researchGatedClaims:[String]
}
public struct HeritageLineageDefinition:Codable,Hashable,Sendable,Identifiable { public var id:String; public var displayName:String; public var vehicles:[HeritageVehicleEngineeringProfile] }

/// Research-safe heritage authoring layer. Names and engineering claims are reference inputs; exact values are not promoted to production truth without verification.
public enum HeritageLineageEngineeringRev29 {
 private static func p(_ id:String,_ lineage:String,_ track:String?=nil,_ era:Int,_ name:String,_ category:HeritageCategory,_ power:String,_ fuel:String,_ induction:String,_ front:String,_ rear:String,_ steering:String,_ mechanisms:[String],_ procedure:String,_ measurement:String)->HeritageVehicleEngineeringProfile {
  .init(id:id,lineageId:lineage,trackId:track,era:era,displayName:name,category:category,powertrainArchitecture:power,fuelMetering:fuel,induction:induction,frontKinematics:front,rearKinematics:rear,steering:steering,dynamicMechanisms:mechanisms,workshopProcedures:[.init(title:procedure,measurementFamily:measurement,researchStatus:.researchPending)],sourceStatus:.researchPending,researchGatedClaims:["exact OEM dimensions","exact torque/clearance/pressure values","factory calibration maps","historical option-specific hardware"])
 }
 private static func compactLineage(_ id:String,_ title:String,_ category:HeritageCategory,_ names:[String],_ themes:[String])->HeritageLineageDefinition {
  .init(id:id,displayName:title,vehicles:names.enumerated().map { i,n in p("\(id)_\(i+1)",id,nil,i+1,n,category,"generation-specific production powertrain","generation-specific fuel system","generation-specific induction","generation-specific front suspension","generation-specific rear suspension","generation-specific steering",[themes[i % themes.count]],"Generation-specific inspection and diagnostic workflow","measurement + telemetry") })
 }
 public static let core14:[HeritageLineageDefinition] = [
  compactLineage("mopar_high_torque","Mopar High-Torque",.muscle,["1968 Charger R/T","1969 Charger Daytona","1970 Challenger R/T Six Pack","1978 Magnum XE","1986 Shelby Charger GLH-S","1999 Charger R/T Concept","2006 Charger SRT8","2015 Challenger SRT Hellcat","2023 Challenger SRT Demon 170"],["axle windup and launch compliance","aero balance migration","multi-carb transient response","electronic spark transient lag","FWD torque steer","prototype throttle/fueling oscillation","brake thermal loading","charge-cooler heat soak","drag weight-transfer sensitivity"]),
  compactLineage("viper_v10","Viper V10 Homologation",.exotic,["1992 Viper RT/10","1996 Viper GTS","1998 Viper GTS-R Homologation","1999 Viper ACR","2003 Viper SRT10 Roadster","2006 Viper SRT10 Coupe","2008 Viper SRT10 ACR","2014 SRT Viper GTS","2017 Viper ACR Extreme Aero"],["engine-braking rear lock tendency","steep tire breakaway","cold tire versus aero window","rough-surface chassis skate","exhaust thermal soak","roll stiffness sensitivity","aero bump-stop coupling","stability-control brake heat","extreme aero tire loading"]),
  compactLineage("bowtie_big_block","Bowtie Big-Block",.muscle,["1967 Camaro SS 396","1969 Camaro COPO 9561","1970 Chevelle SS 454","1979 Camaro Z28","1985 Camaro IROC-Z","1997 Camaro SS","2002 Camaro Z28 35th","2014 Camaro Z/28","2024 Camaro ZL1 1LE"],["leaf-spring axle hop","front mass brake loading","body roll and camber loss","carburetor air-valve transient","torque-arm roll bind","Panhard lateral migration","rear-link compliance steer","cold tire and stiff spring window","solid-cradle NVH and thermal load"]),
  compactLineage("fiberglass_gt","Fiberglass Grand Tourer",.sports,["1963 Corvette Split-Window","1967 Corvette 427 L88","1969 Corvette Stingray 427","1982 Corvette Collector Edition","1990 Corvette ZR-1","1996 Corvette Grand Sport","2002 Corvette Z06","2009 Corvette ZR1","2023 Corvette Z06"],["half-shaft camber coupling","low-speed cooling stress","rear joint play and toe","dual-throttle fueling pulsation","secondary-runner actuation loss","brake-dive rear unloading","torque-tube compliance","supercharger thermal load","high-rpm vibration hardware loosening"]),
  compactLineage("wide_track","Wide-Track Performance",.muscle,["1965 GTO Tri-Power","1969 GTO Judge","1973 Firebird Trans Am SD-455","1977 Firebird Trans Am","1989 Trans Am 20th Anniversary","1996 Firebird Formula WS6","2002 Firebird Trans Am WS6","2006 GTO","2009 G8 GXP"],["front weight and roll","low-vacuum brake assist","downshift inertia","bump-stop understeer","boost-onset oversteer","live-axle surface skip","torque-arm pinion migration","semi-trailing camber/toe","subframe compliance steer"]),
  compactLineage("cadillac_v","V-Series Executive Tourer",.cruiser,["1959 Eldorado Biarritz","1970 Coupe DeVille","1976 Eldorado Convertible","1982 Eldorado Touring Coupe","1993 Allante","2004 CTS-V","2009 CTS-V","2016 CTS-V","2024 CT5-V Blackwing"],["air-leveling imbalance","brake thermal saturation","front-heavy understeer","mixed-material thermal sealing","FWD torque steer and damper faults","differential mount wheel hop","charge-cooler heat soak","stability-control brake heat","cold carbon-brake friction window"]),
  compactLineage("lincoln_luxury","Personal Luxury Speed",.cruiser,["1956 Continental Mark II","1969 Continental Mark III","1976 Continental Mark IV","1980 Continental Mark VI","1984 Mark VII Turbo Diesel","1990 Mark VII LSC","1998 Mark VIII LSC","2017 MKZ 3.0T AWD","2020 Continental Black Label"],["mass and slow steering response","carrier-bearing driveline shudder","soft-suspension brake dive","TV-cable shift pressure sensitivity","air-spring leakage","nonlinear air spring rate","ride-height geometry migration","front-heavy AWD scrub","long-wheelbase yaw response"]),
  compactLineage("fairlady_z","Fairlady Z",.sports,["1969 Fairlady 2000","1971 240Z","1974 260Z","1978 280Z","1979 280ZX","1982 280ZX Turbo","1986 300ZX Turbo Z31","1990 300ZX Twin Turbo Z32","2024 Nissan Z Performance"],["short-wheelbase lift-off rotation","dashpot transient fueling","fuel vapor lock","rear strut toe sensitivity","semi-trailing geometry migration","boost-onset oversteer","temperature-sensor fueling fault","rear-steer yaw sensitivity","rear-subframe compliance"]),
  compactLineage("skyline_heritage","Skyline Heritage",.tuner,["1969 Skyline 2000GT-R Sedan","1971 Skyline 2000GT-R Coupe","1973 Skyline 2000GT-R Kenmeri","1983 Skyline 2000 Turbo RS-X","1987 Skyline GTS-R","1994 Skyline GT-R BNR32","1997 Skyline GT-R V-Spec","2002 Skyline GT-R V-Spec II","2024 GT-R Nismo"],["valve-clearance drift","short-wheelbase lift-off rotation","brake thermal demand","turbo threshold","rear-steer response","AWD torque-transfer understeer","wheelbase agility tradeoff","firm-damper wheel hop","front tire thermal saturation"]),
  compactLineage("toyota_gt","Grand Tourer Twin-Cam",.sports,["1967 Toyota 2000GT","1979 Celica Supra","1985 Celica Supra","1987 Supra 3.0GT Turbo","1990 Supra 2.5GT Twin Turbo R","1993 Supra Twin Turbo","1997 Supra Turbo 15th","2020 GR Supra 3.0","2024 GR Supra 3.0 Manual"],["ground-clearance/bump-stop contact","Panhard lateral migration","semi-trailing toe/camber","head sealing thermal risk","ceramic turbo thermal fragility","sequential boost torque step","intercooler heat soak","short-wheelbase rotation","firm rebound impact response"]),
  compactLineage("toyota_lightweight","Lightweight High-RPM",.tuner,["1972 Celica 1600GT","1974 Corolla Levin TE27","1980 Corolla Levin TE71","1985 Sprinter Trueno AE86","1988 Corolla Levin GT-Z","1995 Sprinter Trueno AE111","1999 Altezza RS200","2013 Toyota 86","2024 GR86"],["front camber loss","leaf-spring bump rotation","exhaust backpressure","Panhard roll steer","supercharged FWD torque steer","complex front-joint wear","high-rpm powerband sensitivity","midrange torque dip","high-G oil pickup sensitivity"]),
  compactLineage("honda_vtec","VTEC Front-Drive",.tuner,["1985 CRX Si","1988 Civic Si EF3","1991 CRX SiR EF8","1995 Civic SiR II EG6","1997 Integra Type R DC2","1998 Civic Type R EK9","2004 Civic Type R EP3","2007 Civic Type R FD2","2024 Civic Type R FL5"],["lowered torsion geometry","rear-bushing lift-off steer","cam-switch traction step","entry understeer","rear-bar lift-off rotation","high-rpm band sensitivity","lowered bump steer","rough-surface skitter","cooling/charge heat soak"]),
  compactLineage("bmw_motorsport","Bavarian Motorsport",.sports,["1973 BMW 3.0 CSL","1974 BMW 2002 Turbo","1980 BMW M1","1988 BMW M3 E30","1990 M3 Sport Evolution","1995 M3 E36 3.2","2003 M3 E46","2011 1 Series M Coupe","2024 M4 Competition"],["semi-trailing lift-off rotation","turbo lag torque step","mid-engine limit rotation","low-rpm momentum loss","curb impact sensitivity","rear bushing compliance steer","bearing/subframe fatigue","short-wheelbase turbo oversteer","brake and front-tire heat"]),
  compactLineage("porsche_rear_engine","Rear-Engine Apex",.exotic,["1967 911S","1973 911 Carrera RS 2.7","1984 911 Carrera 3.2","1989 911 Turbo 3.3","1992 911 Carrera RS 964","1996 911 GT2 993","2004 911 GT3 RS 996","2011 911 GT3 RS 4.0","2024 911 GT3 RS 992"],["rear-CG lift-off rotation","mechanical-injection correlation","manual gearbox synchro sensitivity","turbo-onset oversteer","low-inertia launch/stall sensitivity","rear-engine power oversteer","trail-brake rear unloading","shift-induced balance disturbance","speed-dependent aero balance"])
 ]

 public static let fordTripleWide:HeritageLineageDefinition = {
  let id="ford_triple_wide"
  let a:[(String,String,String,String,String)]=[
   ("1964 Galaxie 500 Lightweight 427 SOHC","SOHC V8","dual carburetors","wishbone/coil","leaf/radius rod"),("1969 Torino Talladega 428CJ","FE V8","4-barrel carburetor","wishbone/coil","live axle/leaf"),("1973 Falcon XB GT Coupe","Cleveland V8","4-barrel carburetor","double wishbone","leaf"),("1985 LTD LX 5.0 Sedan","pushrod V8","electronic injection","MacPherson strut","4-link coil"),("1991 Crown Victoria P72 Interceptor","Windsor V8","carburetor","double wishbone","4-link live axle"),("1993 Thunderbird Super Coupe","supercharged V6","port EFI","independent front","independent rear"),("2003 Marauder / Falcon BA XR8","DOHC V8","port EFI","independent front","Watt-located live axle"),("2014 Falcon FG X XR8","supercharged DOHC V8","port EFI","virtual-pivot wishbone","multi-link IRS"),("2023 Police Interceptor Utility","twin-turbo V6","direct injection","independent front","independent AWD rear")]
  let b:[(String,String,String,String,String)]=[
   ("1965 Lotus Cortina Mk1","twin-cam I4","twin Weber carburetors","MacPherson strut","A-bracket live axle"),("1970 Escort RS1600 BDA","DOHC I4","twin Weber carburetors","MacPherson strut","leaf live axle"),("1973 Capri RS3100 Cologne","V6","dual-choke carburetor","MacPherson strut","leaf/radius rod"),("1986 Sierra RS Cosworth RS500","turbo DOHC I4","electronic injection","MacPherson strut","semi-trailing IRS"),("1989 Taurus SHO","DOHC V6","port EFI","MacPherson strut","independent rear"),("1994 Escort RS Cosworth","turbo DOHC I4","electronic injection","MacPherson strut","semi-trailing AWD"),("2003 Focus RS Mk1","turbo DOHC I4","electronic injection","MacPherson strut","Control Blade IRS"),("2016 Focus RS Mk3","turbo I4","direct injection","MacPherson strut","Twinster AWD rear"),("2024 Puma ST","turbo I3","direct injection","MacPherson strut","torsion beam")]
  let c:[(String,String,String,String,String)]=[
   ("1966 GT40 Mk II","FE V8","4-barrel carburetor","double wishbone","wishbone/trailing links"),("1967 GT40 Mk IV","FE V8","dual carburetors","double wishbone","wishbone/trailing links"),("1972 De Tomaso Pantera GTS","Cleveland V8","4-barrel carburetor","double wishbone","double wishbone"),("1986 RS200 Evolution","turbo I4","electronic injection","twin coil-over wishbone","twin coil-over AWD"),("1990 Supervan 3","high-rpm V8","motorsport injection","pushrod wishbone","pushrod wishbone"),("1995 GT90 Concept","quad-turbo V12","electronic injection","pushrod wishbone","pushrod wishbone"),("2005 Ford GT","supercharged DOHC V8","port EFI","double wishbone","double wishbone"),("2016 Ford GT GTE","twin-turbo V6","direct injection","pushrod race suspension","pushrod race suspension"),("2023 Ford GT Mk IV","twin-turbo V6","direct injection","adaptive race suspension","adaptive race suspension")]
  func makeTrack(_ track:String,_ cat:HeritageCategory,_ rows:[(String,String,String,String,String)],_ mechanisms:[String],_ procedures:[String])->[HeritageVehicleEngineeringProfile] { rows.enumerated().map { i,r in p("ford_\(track)_\(i+1)",id,track,i+1,r.0,cat,r.1,r.2,r.1.contains("turbo") ? "forced induction" : (r.1.contains("supercharged") ? "supercharged" : "atmospheric"),r.3,r.4, i < 3 ? "period steering" : "generation-specific assisted steering",[mechanisms[i]],procedures[i],"physical measurement + telemetry") } }
  let av=makeTrack("heavy_iron",.muscle,a,["timing-drive harmonic sensitivity","high-speed aero load transfer","low-rpm port velocity/fuel dropout","unibody compliance","pursuit brake thermal saturation","supercharger bypass heat soak","Watt-link pivot compliance","boost-driven rear traction breakaway","AWD coupling thermal protection"],["timing-drive tension inspection","radiator pressure-drop/aero probe test","intake velocity/fueling diagnostic","chassis tram measurement","brake pyrometer audit","bypass actuator vacuum test","Watt-link pivot play measurement","virtual-pivot joint lash audit","AWD coupling current/temperature profile"])
  let bv=makeTrack("homologation",.tuner,b,["rear axle housing load concentration","timing-belt contamination sensitivity","front-heavy entry understeer and axle windup","large-turbo torque step","FWD inside-wheel spin","center coupling thermal lockup","helical-LSD steering reaction","rear clutch thermal protection","inside-rear lift under lateral load"],["carburetor synchronization","belt tension and valve-clearance inspection","axle backlash/preload measurement","secondary injector waveform test","intake actuator vacuum test","center coupling breakaway-torque test","rear bushing preload inspection","rear-drive-unit thermal/actuator test","rear spring clocking inspection"])
  let cv=makeTrack("endurance_halo",.exotic,c,["transaxle oil thermal stress","long-tail polar moment","engine-bay fuel/coolant heat soak","AWD driveline lash","crosswind aero yaw","quad-turbo thermal shielding load","half-shaft fastener retention risk","ride-height aero stall sensitivity","cold-slick and high-downforce operating window"],["transaxle backlash/contact-pattern inspection","bonded structure nondestructive inspection","shift linkage and cooling inspection","dual-damper preload balance","race valvetrain service-state check","active-aero actuator synchronization","half-shaft fastener provenance audit","ride-height and underfloor inspection","adaptive damper/ride-height sensor zeroing"])
  return .init(id:id,displayName:"Triple-Wide Ford Heritage (No Mustangs)",vehicles:av+bv+cv)
 }()
 public static let allLineages:[HeritageLineageDefinition] = core14 + [fordTripleWide]
 public static let allVehicles:[HeritageVehicleEngineeringProfile] = allLineages.flatMap(\.vehicles)
 public static var vehicleCount:Int { allVehicles.count }
 public static var lineageCount:Int { allLineages.count }
}
