import Foundation

public enum VehicleDriveLayout:String,Codable,Sendable { case frontEngineRWD, frontEngineAWD, rearEngineRWD, rearEngineAWD, midEngineRWD }
public enum VehicleTransmissionFamily:String,Codable,Sendable { case manual4, manual5, manual6, automatic3, automatic4, dct7, sequential6, prototypeDCT }
public enum VehicleSteeringFamily:String,Codable,Sendable { case recirculatingBall, hydraulicRack, electricRack, motorsportRack }
public enum VehicleBodyFamily:String,Codable,Sendable { case classicFastback, classicGrandTourer, modernCoupe, widebodyTrackCoupe, experimentalGT }

/// Executable fictional production calibration. Exact historical/OEM values remain research-gated.
public struct ProductionVehicleDefinition:Codable,Hashable,Sendable,Identifiable {
 public var id:String
 public var displayName:String
 public var generationId:String
 public var modelYearBand:String
 public var body:VehicleBodyFamily
 public var drive:VehicleDriveLayout
 public var transmission:VehicleTransmissionFamily
 public var steering:VehicleSteeringFamily
 public var massKg:Double
 public var wheelbaseM:Double
 public var trackFrontM:Double
 public var trackRearM:Double
 public var cgHeightM:Double
 public var frontWeightFraction:Double
 public var ratedPowerKW:Double
 public var ratedTorqueNm:Double
 public var redlineRPM:Double
 public var finalDrive:Double
 public var tireSectionFrontMm:Double
 public var tireSectionRearMm:Double
 public var aeroDownforceScale01:Double
 public var brakeThermalCapacity01:Double
 public var coolingCapacity01:Double
 public var chassisRigidity01:Double
 public var serviceComplexity01:Double
 public var diagnosticTechnology:DiagnosticTechnology
 public var signatureFailureMechanisms:[String]
 public var serviceHighlights:[String]
 public var visualIdentity:[String]
 public var researchGates:[String]
 public init(id:String,displayName:String,generationId:String,modelYearBand:String,body:VehicleBodyFamily,drive:VehicleDriveLayout,transmission:VehicleTransmissionFamily,steering:VehicleSteeringFamily,massKg:Double,wheelbaseM:Double,trackFrontM:Double,trackRearM:Double,cgHeightM:Double,frontWeightFraction:Double,ratedPowerKW:Double,ratedTorqueNm:Double,redlineRPM:Double,finalDrive:Double,tireSectionFrontMm:Double,tireSectionRearMm:Double,aeroDownforceScale01:Double,brakeThermalCapacity01:Double,coolingCapacity01:Double,chassisRigidity01:Double,serviceComplexity01:Double,diagnosticTechnology:DiagnosticTechnology,signatureFailureMechanisms:[String],serviceHighlights:[String],visualIdentity:[String],researchGates:[String]) { self.id=id;self.displayName=displayName;self.generationId=generationId;self.modelYearBand=modelYearBand;self.body=body;self.drive=drive;self.transmission=transmission;self.steering=steering;self.massKg=massKg;self.wheelbaseM=wheelbaseM;self.trackFrontM=trackFrontM;self.trackRearM=trackRearM;self.cgHeightM=cgHeightM;self.frontWeightFraction=frontWeightFraction;self.ratedPowerKW=ratedPowerKW;self.ratedTorqueNm=ratedTorqueNm;self.redlineRPM=redlineRPM;self.finalDrive=finalDrive;self.tireSectionFrontMm=tireSectionFrontMm;self.tireSectionRearMm=tireSectionRearMm;self.aeroDownforceScale01=aeroDownforceScale01;self.brakeThermalCapacity01=brakeThermalCapacity01;self.coolingCapacity01=coolingCapacity01;self.chassisRigidity01=chassisRigidity01;self.serviceComplexity01=serviceComplexity01;self.diagnosticTechnology=diagnosticTechnology;self.signatureFailureMechanisms=signatureFailureMechanisms;self.serviceHighlights=serviceHighlights;self.visualIdentity=visualIdentity;self.researchGates=researchGates }
 public var geometry:VehicleGeometry { var g=VehicleGeometry(); g.massKg=massKg; g.wheelbaseM=wheelbaseM; g.cgHeightM=cgHeightM; g.frontTrackM=trackFrontM; g.rearTrackM=trackRearM; g.frontStaticWeightFraction=frontWeightFraction; return g }
}

public enum HeroProductionRosterRev27 {
 public static let vehicles:[ProductionVehicleDefinition] = [
  .init(id:"hero_1967_original",displayName:"1967 Crownfire Original",generationId:"hero_1967",modelYearBand:"1967",body:.classicFastback,drive:.frontEngineRWD,transmission:.manual4,steering:.recirculatingBall,massKg:1390,wheelbaseM:2.74,trackFrontM:1.47,trackRearM:1.47,cgHeightM:0.55,frontWeightFraction:0.55,ratedPowerKW:250,ratedTorqueNm:515,redlineRPM:6200,finalDrive:3.50,tireSectionFrontMm:205,tireSectionRearMm:215,aeroDownforceScale01:0.05,brakeThermalCapacity01:0.35,coolingCapacity01:0.40,chassisRigidity01:0.34,serviceComplexity01:0.28,diagnosticTechnology:.timingLightAndVacuum,signatureFailureMechanisms:["carburetor heat soak","wheel-bearing play","leaf-spring bushing compliance","drum rear brake fade"],serviceHighlights:["analog ignition diagnosis","solid-axle alignment and thrust","carburetor rebuild"],visualIdentity:["compact fastback greenhouse","round lamps","narrow period tires","bright metal bumpers"],researchGates:["exact OEM dimensions","torque values","factory routing"]),
  .init(id:"hero_1968_king",displayName:"1968 Crownfire King",generationId:"hero_1968_kr",modelYearBand:"1968",body:.classicFastback,drive:.frontEngineRWD,transmission:.manual4,steering:.recirculatingBall,massKg:1510,wheelbaseM:2.74,trackFrontM:1.48,trackRearM:1.48,cgHeightM:0.56,frontWeightFraction:0.58,ratedPowerKW:300,ratedTorqueNm:610,redlineRPM:6000,finalDrive:3.70,tireSectionFrontMm:215,tireSectionRearMm:225,aeroDownforceScale01:0.06,brakeThermalCapacity01:0.42,coolingCapacity01:0.50,chassisRigidity01:0.42,serviceComplexity01:0.32,diagnosticTechnology:.timingLightAndVacuum,signatureFailureMechanisms:["fuel starvation under sustained load","coolant heat soak","rear axle backlash","front bushing compliance"],serviceHighlights:["fuel delivery pressure/volume","cooling-system proof","differential contact pattern"],visualIdentity:["deep nose","functional hood extraction","fastback tail","period side graphics"],researchGates:["option-specific routing","OEM torque values"]),
  .init(id:"hero_1970_grand",displayName:"1970 Crownfire Grand",generationId:"hero_1969_70",modelYearBand:"1969-1970",body:.classicGrandTourer,drive:.frontEngineRWD,transmission:.manual4,steering:.recirculatingBall,massKg:1580,wheelbaseM:2.79,trackFrontM:1.51,trackRearM:1.50,cgHeightM:0.55,frontWeightFraction:0.57,ratedPowerKW:290,ratedTorqueNm:590,redlineRPM:6100,finalDrive:3.55,tireSectionFrontMm:225,tireSectionRearMm:235,aeroDownforceScale01:0.10,brakeThermalCapacity01:0.48,coolingCapacity01:0.54,chassisRigidity01:0.46,serviceComplexity01:0.35,diagnosticTechnology:.timingLightAndVacuum,signatureFailureMechanisms:["high-speed front lift","steering-box lash","brake heat saturation","rear axle windup"],serviceHighlights:["caster/camber/toe rack work","steering-center setup","high-speed vibration diagnosis"],visualIdentity:["longer grand-touring nose","quad lamp signature","broad rear quarters","subtle chin aero"],researchGates:["alignment specifications","aero coefficients"]),
  .init(id:"hero_2008_rebirth",displayName:"2008 Crownfire Rebirth",generationId:"hero_2007_09",modelYearBand:"2007-2009",body:.modernCoupe,drive:.frontEngineRWD,transmission:.manual6,steering:.hydraulicRack,massKg:1770,wheelbaseM:2.72,trackFrontM:1.57,trackRearM:1.59,cgHeightM:0.54,frontWeightFraction:0.57,ratedPowerKW:380,ratedTorqueNm:650,redlineRPM:6500,finalDrive:3.73,tireSectionFrontMm:255,tireSectionRearMm:285,aeroDownforceScale01:0.22,brakeThermalCapacity01:0.64,coolingCapacity01:0.68,chassisRigidity01:0.64,serviceComplexity01:0.55,diagnosticTechnology:.obdAndScan,signatureFailureMechanisms:["clutch heat","intercooler heat soak","axle hop","rear bushing windup"],serviceHighlights:["boost leak diagnosis","clutch thermal inspection","driveshaft runout"],visualIdentity:["upright modern fastback","large lower grille","twin hood extraction","wide rear tire stance"],researchGates:["calibration maps","module configuration"]),
  .init(id:"hero_2011_evolution",displayName:"2011 Crownfire Evolution",generationId:"hero_2010_12",modelYearBand:"2010-2012",body:.modernCoupe,drive:.frontEngineRWD,transmission:.manual6,steering:.electricRack,massKg:1715,wheelbaseM:2.72,trackFrontM:1.58,trackRearM:1.60,cgHeightM:0.52,frontWeightFraction:0.56,ratedPowerKW:410,ratedTorqueNm:690,redlineRPM:6800,finalDrive:3.55,tireSectionFrontMm:265,tireSectionRearMm:285,aeroDownforceScale01:0.28,brakeThermalCapacity01:0.70,coolingCapacity01:0.72,chassisRigidity01:0.70,serviceComplexity01:0.62,diagnosticTechnology:.obdAndScan,signatureFailureMechanisms:["EPAS center drift after alignment","supercharger belt slip","rear axle heat","damper fade"],serviceHighlights:["steering center calibration","thermal evidence","four-corner damper inspection"],visualIdentity:["lower nose","projector lamp signature","vented hood","functional rear spoiler"],researchGates:["module coding","exact alignment values"]),
  .init(id:"hero_2014_hammer",displayName:"2014 Crownfire Hammer",generationId:"hero_2013_14",modelYearBand:"2013-2014",body:.widebodyTrackCoupe,drive:.frontEngineRWD,transmission:.manual6,steering:.electricRack,massKg:1740,wheelbaseM:2.72,trackFrontM:1.60,trackRearM:1.61,cgHeightM:0.51,frontWeightFraction:0.56,ratedPowerKW:500,ratedTorqueNm:830,redlineRPM:7000,finalDrive:3.31,tireSectionFrontMm:285,tireSectionRearMm:305,aeroDownforceScale01:0.42,brakeThermalCapacity01:0.82,coolingCapacity01:0.80,chassisRigidity01:0.76,serviceComplexity01:0.68,diagnosticTechnology:.canTelemetry,signatureFailureMechanisms:["tire thermal overload","driveshaft resonance","differential temperature rise","high-speed aero sensitivity"],serviceHighlights:["order-tracked vibration diagnosis","differential backlash","high-speed verification"],visualIdentity:["deep splitter","large heat-extraction hood","wide rear haunches","high-speed aero package"],researchGates:["V-max aero coefficients","CAN identifiers"]),
  .init(id:"hero_2022_apex",displayName:"2022 Crownfire Apex",generationId:"hero_2020_22",modelYearBand:"2020-2022",body:.widebodyTrackCoupe,drive:.frontEngineRWD,transmission:.dct7,steering:.electricRack,massKg:1890,wheelbaseM:2.72,trackFrontM:1.63,trackRearM:1.65,cgHeightM:0.49,frontWeightFraction:0.55,ratedPowerKW:570,ratedTorqueNm:850,redlineRPM:7600,finalDrive:3.73,tireSectionFrontMm:305,tireSectionRearMm:315,aeroDownforceScale01:0.72,brakeThermalCapacity01:0.92,coolingCapacity01:0.94,chassisRigidity01:0.90,serviceComplexity01:0.84,diagnosticTechnology:.canTelemetry,signatureFailureMechanisms:["DCT thermal protection","front tire shoulder overheating","hub temperature rise","network/calibration mismatch"],serviceHighlights:["DCT thermal proof","IRS alignment","CAN telemetry correlation","track verification"],visualIdentity:["low technical nose","large heat extractors","broad track","integrated track aero"],researchGates:["CAN messages","module pinouts","exact OEM values"]),
  .init(id:"hero_exp_lab",displayName:"Crownfire EXP Laboratory",generationId:"hero_exp",modelYearBand:"Experimental",body:.experimentalGT,drive:.frontEngineRWD,transmission:.sequential6,steering:.motorsportRack,massKg:1620,wheelbaseM:2.76,trackFrontM:1.68,trackRearM:1.70,cgHeightM:0.45,frontWeightFraction:0.52,ratedPowerKW:650,ratedTorqueNm:900,redlineRPM:8200,finalDrive:3.45,tireSectionFrontMm:315,tireSectionRearMm:335,aeroDownforceScale01:0.88,brakeThermalCapacity01:0.96,coolingCapacity01:0.96,chassisRigidity01:0.95,serviceComplexity01:0.90,diagnosticTechnology:.canTelemetry,signatureFailureMechanisms:["prototype mount fatigue","calibration instability","fabricated-line heat exposure","aero platform sensitivity"],serviceHighlights:["fabrication inspection","strain/thermal instrumentation","setup DOE"],visualIdentity:["removable development panels","sensor ports","flat floor","adjustable aero"],researchGates:["all prototype values"]),
  .init(id:"legend_gtx_bloodline_zero",displayName:"Legend GT-X Bloodline Zero",generationId:"legend_gtx",modelYearBand:"Endgame",body:.experimentalGT,drive:.frontEngineRWD,transmission:.prototypeDCT,steering:.motorsportRack,massKg:1690,wheelbaseM:2.78,trackFrontM:1.70,trackRearM:1.72,cgHeightM:0.43,frontWeightFraction:0.50,ratedPowerKW:820,ratedTorqueNm:1100,redlineRPM:9000,finalDrive:3.30,tireSectionFrontMm:325,tireSectionRearMm:345,aeroDownforceScale01:1.0,brakeThermalCapacity01:1.0,coolingCapacity01:1.0,chassisRigidity01:1.0,serviceComplexity01:1.0,diagnosticTechnology:.canTelemetry,signatureFailureMechanisms:["extreme thermal density","aero ride-height coupling","driveline torsional resonance","high-energy tire degradation"],serviceHighlights:["full instrumentation","proof-based calibration","corner-weight/alignment synthesis","dyno-to-road verification"],visualIdentity:["bloodline silhouette cues","active aero surfaces","serviceable body modules","visible engineering instrumentation"],researchGates:["all exact unverified values"])
 ]
 public static func vehicle(_ id:String)->ProductionVehicleDefinition? { vehicles.first{$0.id==id} }
}
