import Foundation
import WTRLCore

public enum ComponentCategory: String, Codable, CaseIterable, Sendable { case engine, fuel, cooling, electrical, brakes, suspension, transmission, differential, axle, clutch, tire, body, chassis, other }
public struct ComponentInstallation: Codable, Hashable, Sendable { public var slot:String; public var componentInstanceId:String; public init(slot:String,componentInstanceId:String){self.slot=slot;self.componentInstanceId=componentInstanceId} }
public struct ComponentInstance: Codable, Hashable, Sendable, Identifiable {
    public var id:String { componentInstanceId }; public var componentInstanceId:String; public var specificationId:String; public var category:ComponentCategory; public var condition01:Double; public var wear01:Double; public var installed:Bool; public var currentVehicleInstanceId:String?; public var history:[EvidenceRecord]
    public init(componentInstanceId:String=UUID().uuidString,specificationId:String,category:ComponentCategory,condition01:Double=1,wear01:Double=0,installed:Bool=false,currentVehicleInstanceId:String?=nil,history:[EvidenceRecord]=[]){self.componentInstanceId=componentInstanceId;self.specificationId=specificationId;self.category=category;self.condition01=condition01;self.wear01=wear01;self.installed=installed;self.currentVehicleInstanceId=currentVehicleInstanceId;self.history=history}
}
public struct VehicleCalibrationState: Codable, Hashable, Sendable { public var revisionId="baseline", version="baseline", operatingMode="Road", sourceDynoRunId=""; public var revLimitRpm=0.0, finalDriveOverride=0.0; public var torqueBandScales=[Double](repeating:1,count:8); public var globalTorqueScale=1.0, fuelConservation01=0.0, thermalProtection01=0.0; public var validated=false; public init(){} }
public struct VehicleInstance: Codable, Hashable, Sendable, Identifiable {
    public var id:String { vehicleInstanceId }; public var vehicleInstanceId:String; public var platformId:String; public var chassisInstanceId:String; public var nickname:String; public var acquiredAt:Date; public var mileageKm:Double; public var installations:[ComponentInstallation]; public var history:[EvidenceRecord]; public var calibration:VehicleCalibrationState; public var fuelLiters:Double; public var fuelCapacityLiters:Double; public var lifetimeFuelUsedLiters:Double
    public init(vehicleInstanceId:String=UUID().uuidString,platformId:String,chassisInstanceId:String=UUID().uuidString,nickname:String="",acquiredAt:Date=Date(),mileageKm:Double=0,installations:[ComponentInstallation]=[],history:[EvidenceRecord]=[],calibration: VehicleCalibrationState = .init(),fuelLiters:Double=60,fuelCapacityLiters:Double=60,lifetimeFuelUsedLiters:Double=0){self.vehicleInstanceId=vehicleInstanceId;self.platformId=platformId;self.chassisInstanceId=chassisInstanceId;self.nickname=nickname;self.acquiredAt=acquiredAt;self.mileageKm=mileageKm;self.installations=installations;self.history=history;self.calibration=calibration;self.fuelLiters=fuelLiters;self.fuelCapacityLiters=fuelCapacityLiters;self.lifetimeFuelUsedLiters=lifetimeFuelUsedLiters}
}
