import Foundation

public enum EngineLayoutRev38:String,Codable,Sendable { case inline3, inline4, inline6, flat6, v6, v8, v10, v12, hybridV8, turbineHybrid, unknown }
public enum DrivetrainLayoutRev38:String,Codable,Sendable { case frontRWD, frontFWD, frontAWD, midRWD, midAWD, rearRWD, rearAWD, frontRearTransaxleRWD, unknown }
public enum SuspensionFamilyRev38:String,Codable,Sendable { case liveAxleLeaf, liveAxleCoilLink, torsionBarLiveAxle, macPherson, doubleWishbone, semiTrailingArm, multiLink, twistBeam, transverseLeafIRS, airAdaptive, magneticAdaptive, spoolValve, pushrodInboard, activePredictive, mixed, unknown }
public struct VehicleEngineeringTruthRev38:Codable,Hashable,Sendable,Identifiable {
 public var id:String; public var engineDescription:String; public var transmissionDescription:String; public var drivetrain:DrivetrainLayoutRev38; public var frontSuspension:SuspensionFamilyRev38; public var rearSuspension:SuspensionFamilyRev38; public var dampingTechnology:String; public var sourceStatus:EngineeringProvenance; public var researchGates:[String]
}
/// Engineering-family truth used by physics, inspection and service authoring. Real-world names/specifications remain research leads until verified.
public enum VehicleEngineeringTruthCatalogRev38 {
 public static func profile(for entry:VehicleCatalogEntryRev36)->VehicleEngineeringTruthRev38 {
 let n = entry.displayName.lowercased()
 var engine = "generation-specific engine; verify exact application"; var tx = "generation-specific transmission; verify exact application"
 var drive:DrivetrainLayoutRev38 = .frontRWD; var f:SuspensionFamilyRev38 = .doubleWishbone; var r:SuspensionFamilyRev38 = .liveAxleLeaf; var damping = "passive hydraulic"
 if n.contains("focus rs") { engine = n.contains("2016") ? "2.3L turbocharged inline-4 reference" : "2.0L turbocharged inline-4 reference"; tx = "manual transaxle / AWD coupling as generation applicable"; drive = n.contains("2016") ? .frontAWD:.frontFWD; f = .macPherson; r = .multiLink; damping = n.contains("2016") ? "switchable electronic damping":"performance passive damping" }
 else if n.contains("gt40") || n.contains("pantera") || n.contains("ford gt") || n.contains("rs200") || n.contains("gt90") || n.contains("supervan") { drive = n.contains("rs200") ? .midAWD:.midRWD; f = n.contains("gte") || n.contains("mk iv") || n.contains("supervan") ? .pushrodInboard:.doubleWishbone; r = f; tx = "rear transaxle, generation-specific"; damping = f == .pushrodInboard ? "motorsport inboard damping":"coil-over performance damping" }
 else if n.contains("911") { engine = "rear-mounted flat-6, generation-specific"; tx = "rear transaxle, generation-specific"; drive = .rearRWD; f = .macPherson; r = n.contains("993") || n.contains("992") ? .multiLink:.semiTrailingArm; if n.contains("992") { f = .pushrodInboard; damping = "multi-adjustable track damping with active aero integration" } }
 else if n.contains("civic") || n.contains("crx") || n.contains("integra") { drive = .frontFWD; tx = "transverse manual transaxle, generation-specific"; f = n.contains("fl5") ? .macPherson:.doubleWishbone; r = n.contains("ep3") || n.contains("fl5") ? .multiLink:.doubleWishbone; damping = n.contains("fl5") ? "adaptive damping":"performance passive damping" }
 else if n.contains("skyline") || n.contains("gt-r") { drive = (n.contains("bnr") || n.contains("v-spec") || n.contains("nismo")) ? .frontAWD:.frontRWD; f = n.contains("1969") || n.contains("1971") ? .macPherson:.multiLink; r = n.contains("1969") || n.contains("1971") || n.contains("1983") ? .semiTrailingArm:.multiLink; tx = "generation-specific manual/DCT and AWD transfer system" }
 else if n.contains("corvette") { drive = n.contains("2023") ? .midRWD:.frontRearTransaxleRWD; f = .doubleWishbone; r = n.contains("1963") || n.contains("1967") || n.contains("1969") || n.contains("1982") ? .transverseLeafIRS:.doubleWishbone; damping = n.contains("zr1") || n.contains("z06") ? "adaptive/track damping as generation applicable":"passive performance damping" }
 else if n.contains("viper") { engine = "OHV V10, generation-specific"; tx = "6-speed longitudinal manual reference"; f = .doubleWishbone; r = .doubleWishbone; damping = n.contains("acr") ? "multi-adjustable motorsport coil-over":"performance monotube" }
 else if n.contains("crownfire apex") { engine = "5.2L supercharged cross-plane V8 fictional production calibration"; tx = "7-speed rear dual-clutch transaxle"; drive = .frontRearTransaxleRWD; f = .pushrodInboard; r = .pushrodInboard; damping = "active electronic ride-height / inboard damping" }
 else if n.contains("apex revenant") { engine = "GTD-inspired development V8 baseline; ultimate experimental V12 program unlocks after certification"; tx = "rear transaxle development architecture"; drive = .frontRearTransaxleRWD; f = .pushrodInboard; r = .pushrodInboard; damping = "active predictive telemetry-linked damping" }
 else if n.contains("challenger") || n.contains("charger") || n.contains("magnum") { f = .torsionBarLiveAxle; r = n.contains("2006") || n.contains("2015") || n.contains("2023") ? .multiLink:.liveAxleLeaf; damping = n.contains("hellcat") || n.contains("demon") ? "adaptive damping":"passive performance damping" }
 else if n.contains("mustang") || n.contains("shelby") || n.contains("boss") || n.contains("bullitt") { f = .macPherson; r = (n.contains("2000") || n.contains("2003") || n.contains("2019") || n.contains("2020") || n.contains("2022") || n.contains("2024") || n.contains("gtd")) ? .multiLink:.liveAxleLeaf; damping = (n.contains("2019") || n.contains("2020") || n.contains("2022") || n.contains("2024")) ? "magnetorheological/adaptive reference":"passive performance damping" }
 let provenance:EngineeringProvenance = entry.researchGated ? .researchPending:.fictionalProductionCalibration
 return .init(id:entry.id,engineDescription:engine,transmissionDescription:tx,drivetrain:drive,frontSuspension:f,rearSuspension:r,dampingTechnology:damping,sourceStatus:provenance,researchGates:entry.researchGated ? ["verify exact engine option/year","verify transmission application","verify suspension geometry/damping","verify output, ratios, dimensions and calibration"]:[])
 }
 public static let profiles:[VehicleEngineeringTruthRev38] = CompleteVehicleCatalogRev36.entries.map(profile)
 public static var completeCoverage:Bool { profiles.count == CompleteVehicleCatalogRev36.playerFacingCount && Set(profiles.map(\.id)).count == profiles.count }
}
