import Foundation
import WTRLVehicle

public enum EnforcementRole:String,Codable,Sendable { case patrol, highwayInterceptor, containment, specialResponse, stateHunter }
public struct EnforcementVehicleDefinition:Codable,Hashable,Sendable,Identifiable {
 public var id:String; public var displayName:String; public var role:EnforcementRole; public var tier:EnforcementTier
 public var platform:ProductionVehicleDefinition; public var durability01:Double; public var brakeEndurance01:Double; public var pursuitCooling01:Double; public var offRoad01:Double
 public var equipment:[String]; public var behavior:[String]; public var visualIdentity:[String]
 public var fleetProfile:EnforcementUnitProfile { .init(id:id,tier:tier,massKg:platform.massKg,powerKW:platform.ratedPowerKW,maxSpeedMps:max(45,min(86,platform.ratedPowerKW/8.0)),cornering01:max(0.25,min(0.96,0.35+platform.chassisRigidity01*0.6)),containment01:durability01) }
}
public enum EnforcementProductionRosterRev27 {
 public static let vehicles:[EnforcementVehicleDefinition] = [
  .init(id:"sentinel_county_v8",displayName:"Sentinel County V8",role:.patrol,tier:.county,platform:.init(id:"sentinel_county_platform",displayName:"Sentinel County Platform",generationId:"enforcement_county",modelYearBand:"Current",body:.modernCoupe,drive:.frontEngineRWD,transmission:.automatic4,steering:.electricRack,massKg:1940,wheelbaseM:2.94,trackFrontM:1.62,trackRearM:1.62,cgHeightM:0.55,frontWeightFraction:0.54,ratedPowerKW:260,ratedTorqueNm:470,redlineRPM:6500,finalDrive:3.27,tireSectionFrontMm:255,tireSectionRearMm:255,aeroDownforceScale01:0.18,brakeThermalCapacity01:0.72,coolingCapacity01:0.78,chassisRigidity01:0.72,serviceComplexity01:0.58,diagnosticTechnology:.canTelemetry,signatureFailureMechanisms:["brake heat after repeated stops","front hub heat","idle heat soak"],serviceHighlights:["fleet brake inspection","hub temperature trend","cooling pressure test"],visualIdentity:["four-door pursuit silhouette","push bar","roof light package"],researchGates:["fictional production calibration"]),durability01:0.70,brakeEndurance01:0.72,pursuitCooling01:0.78,offRoad01:0.35,equipment:["marked light package","front push structure","roadside evidence camera"],behavior:["observe","follow","traffic containment"],visualIdentity:["county livery","high-visibility markings","steel pursuit wheels"]),
  .init(id:"vector_highway_interceptor",displayName:"Vector Highway Interceptor",role:.highwayInterceptor,tier:.highway,platform:.init(id:"vector_platform",displayName:"Vector Interceptor Platform",generationId:"enforcement_highway",modelYearBand:"Current",body:.modernCoupe,drive:.frontEngineAWD,transmission:.dct7,steering:.electricRack,massKg:1760,wheelbaseM:2.83,trackFrontM:1.64,trackRearM:1.65,cgHeightM:0.49,frontWeightFraction:0.53,ratedPowerKW:390,ratedTorqueNm:620,redlineRPM:7200,finalDrive:3.55,tireSectionFrontMm:285,tireSectionRearMm:285,aeroDownforceScale01:0.45,brakeThermalCapacity01:0.90,coolingCapacity01:0.90,chassisRigidity01:0.88,serviceComplexity01:0.78,diagnosticTechnology:.canTelemetry,signatureFailureMechanisms:["AWD coupling heat","front tire thermal saturation","brake rotor heat checking"],serviceHighlights:["AWD thermal inspection","four-corner tire analysis","high-speed brake proof"],visualIdentity:["low four-door fastback","integrated lightbar","deep cooling openings"],researchGates:["fictional production calibration"]),durability01:0.74,brakeEndurance01:0.91,pursuitCooling01:0.91,offRoad01:0.30,equipment:["low-profile emergency lighting","forward observation package","heavy-duty cooling"],behavior:["intercept","parallel shadow","highway cutoff"],visualIdentity:["dark highway graphics","low roof lighting","aero wheel covers"]),
  .init(id:"rhino_heavy_containment",displayName:"Rhino Heavy Containment",role:.containment,tier:.heavyContainment,platform:.init(id:"rhino_platform",displayName:"Rhino Containment Platform",generationId:"enforcement_heavy",modelYearBand:"Current",body:.experimentalGT,drive:.frontEngineAWD,transmission:.automatic4,steering:.electricRack,massKg:4050,wheelbaseM:3.35,trackFrontM:1.82,trackRearM:1.82,cgHeightM:0.72,frontWeightFraction:0.55,ratedPowerKW:430,ratedTorqueNm:980,redlineRPM:6000,finalDrive:4.10,tireSectionFrontMm:315,tireSectionRearMm:315,aeroDownforceScale01:0.04,brakeThermalCapacity01:0.94,coolingCapacity01:0.96,chassisRigidity01:0.92,serviceComplexity01:0.82,diagnosticTechnology:.canTelemetry,signatureFailureMechanisms:["tire shoulder heat","brake mass heat soak","driveline joint load"],serviceHighlights:["heavy brake thermal inspection","driveshaft joint inspection","chassis datum check"],visualIdentity:["armored utility silhouette","wide stance","protected lighting"],researchGates:["fictional production calibration"]),durability01:0.98,brakeEndurance01:0.94,pursuitCooling01:0.96,offRoad01:0.82,equipment:["reinforced containment structure","run-flat fleet tires","scene lighting"],behavior:["roadblock","corridor closure","low-speed containment"],visualIdentity:["matte containment panels","protected lamps","heavy steel wheels"]),
  .init(id:"phantom_special_response",displayName:"Phantom Special Response",role:.specialResponse,tier:.specialInterdiction,platform:.init(id:"phantom_platform",displayName:"Phantom Response Platform",generationId:"enforcement_special",modelYearBand:"Current",body:.widebodyTrackCoupe,drive:.frontEngineAWD,transmission:.dct7,steering:.motorsportRack,massKg:1580,wheelbaseM:2.70,trackFrontM:1.67,trackRearM:1.68,cgHeightM:0.44,frontWeightFraction:0.52,ratedPowerKW:455,ratedTorqueNm:680,redlineRPM:7900,finalDrive:3.80,tireSectionFrontMm:305,tireSectionRearMm:305,aeroDownforceScale01:0.76,brakeThermalCapacity01:0.97,coolingCapacity01:0.94,chassisRigidity01:0.96,serviceComplexity01:0.90,diagnosticTechnology:.canTelemetry,signatureFailureMechanisms:["aero platform sensitivity","tire heat","AWD coupling thermal load"],serviceHighlights:["corner-weight setup","aero ride-height verification","thermal tire analysis"],visualIdentity:["compact widebody coupe","concealed emergency lighting","large diffuser"],researchGates:["fictional production calibration"]),durability01:0.66,brakeEndurance01:0.98,pursuitCooling01:0.95,offRoad01:0.20,equipment:["concealed emergency package","air support datalink","track-grade telemetry"],behavior:["precision intercept","crest-zone response","coordinated cutoff"],visualIdentity:["minimal markings","blackout trim","functional track aero"]),
  .init(id:"apex_state_hunter",displayName:"Apex State Hunter",role:.stateHunter,tier:.stateHunter,platform:.init(id:"apex_hunter_platform",displayName:"Apex Hunter Platform",generationId:"enforcement_hunter",modelYearBand:"Prototype",body:.experimentalGT,drive:.frontEngineAWD,transmission:.prototypeDCT,steering:.motorsportRack,massKg:1660,wheelbaseM:2.76,trackFrontM:1.70,trackRearM:1.71,cgHeightM:0.43,frontWeightFraction:0.51,ratedPowerKW:600,ratedTorqueNm:880,redlineRPM:8500,finalDrive:3.60,tireSectionFrontMm:315,tireSectionRearMm:325,aeroDownforceScale01:0.92,brakeThermalCapacity01:1.0,coolingCapacity01:1.0,chassisRigidity01:0.99,serviceComplexity01:0.98,diagnosticTechnology:.canTelemetry,signatureFailureMechanisms:["extreme tire energy","DCT thermal density","aero floor damage"],serviceHighlights:["full telemetry inspection","floor/aero datum check","DCT thermal proof"],visualIdentity:["purpose-built pursuit GT","active aero","flush emergency lighting"],researchGates:["fictional prototype calibration"]),durability01:0.82,brakeEndurance01:1.0,pursuitCooling01:1.0,offRoad01:0.18,equipment:["state pursuit telemetry","multi-unit coordination","high-speed evidence recorder"],behavior:["statewide hunter response","high-speed shadow","coordinated containment"],visualIdentity:["state hunter insignia","active aero","low-signature light system"])
 ]
 public static func vehicle(_ id:String)->EnforcementVehicleDefinition? { vehicles.first{$0.id==id} }
}
