import Foundation
import WTRLVehicle

public struct BearingInspectionReport:Codable,Hashable,Sendable { public var unloadedPlayMm:Double,loadedPlayMm:Double,rotationRoughness01:Double,temperatureC:Double;public var severity01:Double;public var findings:[String] }
public enum BearingInspectionAuthority { public static func inspect(damage01:Double,loosenessMm:Double,temperatureC:Double,radialLoadN:Double)->BearingInspectionReport {let d=max(0,min(1,damage01));let unloaded=max(0,loosenessMm+d*0.18);let loaded=unloaded*(1+min(1,radialLoadN/6000)*0.55);let rough=min(1,d*0.85+max(0,temperatureC-70)/100);var f:[String]=[];if loaded>0.25{f.append("loaded bearing play exceeds modeled envelope")};if rough>0.35{f.append("rotation roughness supports bearing damage hypothesis")};if temperatureC>90{f.append("bearing temperature is elevated")};return .init(unloadedPlayMm:unloaded,loadedPlayMm:loaded,rotationRoughness01:rough,temperatureC:temperatureC,severity01:min(1,max(d,rough)),findings:f)} }

public struct SteeringJointInspectionReport:Codable,Hashable,Sendable { public var freePlayMm:Double,loadedDeflectionMm:Double,bendIndex01:Double,bootIntegrity01:Double;public var serviceRequired:Bool }
public enum SteeringJointInspectionAuthority { public static func inspect(damage01:Double,loosenessMm:Double,appliedLoadN:Double,bootIntegrity01:Double=1)->SteeringJointInspectionReport {let d=max(0,min(1,damage01));let free=max(0,loosenessMm+d*1.8);let loaded=free+max(0,appliedLoadN)/5000*(0.25+d);return .init(freePlayMm:free,loadedDeflectionMm:loaded,bendIndex01:d,bootIntegrity01:max(0,min(1,bootIntegrity01)),serviceRequired:d>0.2 || free>0.6 || bootIntegrity01<0.4)} }

public struct BushingComplianceReport:Codable,Hashable,Sendable { public var longitudinalMm:Double,lateralMm:Double,verticalMm:Double,hysteresisMm:Double;public var dynamicToeRiskDeg:Double;public var serviceRequired:Bool }
public enum BushingComplianceAuthority { public static func inspect(damage01:Double,appliedLoadN:Double)->BushingComplianceReport {let d=max(0,min(1,damage01)),l=max(0,appliedLoadN)/1000;let longitudinal=l*(0.35+1.6*d),lateral=l*(0.22+1.15*d),vertical=l*(0.12+0.65*d),h=(longitudinal+lateral)*0.12*d;return .init(longitudinalMm:longitudinal,lateralMm:lateral,verticalMm:vertical,hysteresisMm:h,dynamicToeRiskDeg:lateral*0.08,serviceRequired:d>0.35 || lateral>1.5)} }

public struct DamperInspectionReport:Codable,Hashable,Sendable { public var availableTravelMm:Double,usedTravelMm:Double,reboundRatio01:Double,thermalFade01:Double,leakSeverity01:Double;public var serviceRequired:Bool }
public enum DamperInspectionAuthority { public static func inspect(nominalTravelMm:Double,measuredTravelMm:Double,temperatureC:Double,leakSeverity01:Double)->DamperInspectionReport {let leak=max(0,min(1,leakSeverity01)),fade=min(1,max(0,temperatureC-85)/100+leak*0.55);let rebound=max(0.05,1-fade);return .init(availableTravelMm:max(0,nominalTravelMm),usedTravelMm:max(0,measuredTravelMm),reboundRatio01:rebound,thermalFade01:fade,leakSeverity01:leak,serviceRequired:fade>0.35 || leak>0.2 || measuredTravelMm>nominalTravelMm*0.95)} }

public struct DriveshaftInspectionReport:Codable,Hashable,Sendable { public var runoutMm:Double,operatingAngleDeg:Double,phaseErrorDeg:Double,dominantOrder:Double,resonanceRisk01:Double;public var findings:[String] }
public enum DriveshaftInspectionAuthority { public static func inspect(runoutMm:Double,operatingAngleDeg:Double,phaseErrorDeg:Double,shaftRPM:Double,vibrationHz:Double)->DriveshaftInspectionReport {let order=vibrationHz/max(1,shaftRPM/60);let risk=min(1,max(0,runoutMm/1.2)+abs(phaseErrorDeg)/45+max(0,operatingAngleDeg-4)/10);var f:[String]=[];if runoutMm>0.6{f.append("shaft runout is elevated")};if abs(order-1)<0.2{f.append("vibration is consistent with first-order shaft excitation")};if abs(order-2)<0.25{f.append("second-order driveline excitation is present")};return .init(runoutMm:runoutMm,operatingAngleDeg:operatingAngleDeg,phaseErrorDeg:phaseErrorDeg,dominantOrder:order,resonanceRisk01:min(1,risk),findings:f)} }

public struct ChassisDatumReport:Codable,Hashable,Sendable { public var leftDiagonalMm:Double,rightDiagonalMm:Double,diagonalDifferenceMm:Double,twistIndex01:Double;public var structuralInspectionRequired:Bool }
public enum ChassisDatumAuthority { public static func inspect(leftDiagonalMm:Double,rightDiagonalMm:Double)->ChassisDatumReport {let diff=abs(leftDiagonalMm-rightDiagonalMm);return .init(leftDiagonalMm:leftDiagonalMm,rightDiagonalMm:rightDiagonalMm,diagonalDifferenceMm:diff,twistIndex01:min(1,diff/18),structuralInspectionRequired:diff>4)} }
