import Foundation
import WTRLVehicle
public struct RemovedPartInventoryRecordRev33:Codable,Hashable,Sendable,Identifiable { public var id:String { component.componentInstanceId }; public var component:InstalledComponentBindingRev32; public var removedFromSlot:String; public var disposition:String; public var serviceNotes:[String] }
public struct ProductionServiceRuntimeRev33:Codable,Hashable,Sendable { public var state:ServiceableVehicleStateRev32; public var plans:[String:ProductionServicePlanRev33]; public var removedInventory:[RemovedPartInventoryRecordRev33] }
public enum ProductionServiceRuntimeAuthorityRev33 {
 public static func seed(vehicleInstanceId:String,platform:HeritageVehicleEngineeringProfile)->ProductionServiceRuntimeRev33 { .init(state:ServiceConnectionAuthorityRev32.seed(vehicleInstanceId:vehicleInstanceId,platform:platform),plans:Dictionary(uniqueKeysWithValues:ProductionServicePlanAuthorityRev33.plans(for:platform).map{($0.componentNodeId,$0)}),removedInventory:[]) }
 public static func setInterface(slot:String,interfaceId:String,to newState:ServiceInterfaceStateRev33,runtime:inout ProductionServiceRuntimeRev33){ guard var p=runtime.plans[slot],let idx=p.interfaces.firstIndex(where:{$0.id==interfaceId}) else{return}; p.interfaces[idx].state=newState; runtime.plans[slot]=p }
 public static func remove(slot:String,runtime:inout ProductionServiceRuntimeRev33)->Bool { guard let p=runtime.plans[slot],ProductionServicePlanAuthorityRev33.canExtract(p),var c=runtime.state.assembly.components[slot] else{return false}; c.lifecycle = .removed; c.history.append("removed from \(slot)"); runtime.state.assembly.components[slot]=c; runtime.removedInventory.append(.init(component:c,removedFromSlot:slot,disposition:p.rebuildable ? "inspect/rebuild/replace" : "inspect/replace",serviceNotes:[])); return true }
 public static func installReplacement(slot:String,serial:String,runtime:inout ProductionServiceRuntimeRev33)->Bool { guard let old=runtime.state.assembly.components[slot] else{return false}; var n=DurableComponentIdentityAuthorityRev32.replacement(for:old,newSerial:serial); n.lifecycle = .installed; n.history.append("installed at \(slot); torque/calibration verification pending"); runtime.state.assembly.components[slot]=n; return true }
}
