import Foundation
import WTRLVehicle

public enum EngineOrientation: String,Codable,Sendable { case longitudinal, transverse, rearLongitudinal }
public enum SumpOrientation:String,Codable,Sendable { case front,rear,center,dry }
public struct ChassisPackagingEnvelope:Codable,Hashable,Sendable { public var bayLengthMm:Double,bayWidthMm:Double,bayHeightMm:Double,tunnelWidthMm:Double,frontAxleCapacityKg:Double;public var orientation:EngineOrientation; public init(bayLengthMm:Double,bayWidthMm:Double,bayHeightMm:Double,tunnelWidthMm:Double,frontAxleCapacityKg:Double,orientation:EngineOrientation){self.bayLengthMm=bayLengthMm;self.bayWidthMm=bayWidthMm;self.bayHeightMm=bayHeightMm;self.tunnelWidthMm=tunnelWidthMm;self.frontAxleCapacityKg=frontAxleCapacityKg;self.orientation=orientation} }
public struct PowertrainPackage:Codable,Hashable,Sendable { public var lengthMm:Double,widthMm:Double,heightMm:Double,massKg:Double,gearboxWidthMm:Double;public var orientation:EngineOrientation,sump:SumpOrientation;public init(lengthMm:Double,widthMm:Double,heightMm:Double,massKg:Double,gearboxWidthMm:Double,orientation:EngineOrientation,sump:SumpOrientation){self.lengthMm=lengthMm;self.widthMm=widthMm;self.heightMm=heightMm;self.massKg=massKg;self.gearboxWidthMm=gearboxWidthMm;self.orientation=orientation;self.sump=sump} }
public enum FabricationOperation:String,Codable,CaseIterable,Sendable { case motorMounts,bellhousingAdapter,tunnelClearance,subframeFabrication,oilPanConversion,steeringClearance,coolingConversion,wiringHarness,driveshaft,axleReinforcement,brakeUpgrade,structuralReinforcement }
public struct SwapAssessment:Codable,Hashable,Sendable { public var feasible:Bool,fitMarginMm:Double,frontAxleUtilization01:Double,operations:[FabricationOperation],estimatedHours:Int,estimatedCredits:Int;public init(feasible:Bool,fitMarginMm:Double,frontAxleUtilization01:Double,operations:[FabricationOperation],estimatedHours:Int,estimatedCredits:Int){self.feasible=feasible;self.fitMarginMm=fitMarginMm;self.frontAxleUtilization01=frontAxleUtilization01;self.operations=operations;self.estimatedHours=estimatedHours;self.estimatedCredits=estimatedCredits} }
public enum UniversalFabricationAuthority { public static func assess(chassis:ChassisPackagingEnvelope,powertrain:PowertrainPackage)->SwapAssessment { var ops:[FabricationOperation]=[.motorMounts,.wiringHarness,.coolingConversion,.driveshaft];let lengthMargin=chassis.bayLengthMm-powertrain.lengthMm,widthMargin=chassis.bayWidthMm-powertrain.widthMm,heightMargin=chassis.bayHeightMm-powertrain.heightMm,fit=min(lengthMargin,min(widthMargin,heightMargin));if fit < -140{return .init(feasible:false,fitMarginMm:fit,frontAxleUtilization01:1,operations:[],estimatedHours:0,estimatedCredits:0)};if fit<0{ops += [.subframeFabrication,.structuralReinforcement]};if powertrain.gearboxWidthMm>chassis.tunnelWidthMm{ops.append(.tunnelClearance)};if chassis.orientation != powertrain.orientation{ops += [.subframeFabrication,.bellhousingAdapter]};if powertrain.sump != .rear && powertrain.sump != .dry{ops += [.oilPanConversion,.steeringClearance]};let axleUse=powertrain.massKg/max(1,chassis.frontAxleCapacityKg);if axleUse>0.58{ops += [.axleReinforcement,.brakeUpgrade]};ops=Array(Set(ops)).sorted{$0.rawValue<$1.rawValue};let hours=ops.reduce(0){$0 + ($1 == .structuralReinforcement ? 28 : $1 == .subframeFabrication ? 24 : 8)};return .init(feasible:true,fitMarginMm:fit,frontAxleUtilization01:axleUse,operations:ops,estimatedHours:hours,estimatedCredits:hours*145) } }
